### ISSUE TITLE
[Feature Request]: Please consider a port to FreeBSD ..

### ISSUE THREAD

**Issue by bmentink** [JaKooLit/Fedora-Hyprland#102]
Great bunch of scripts. Fedora  & Arch  are my favourite Linux's, but now days I prefer to run Hyprland on FreeBSD. Runs much faster and BSD is much cleaner at the OS level..

However, there are not too many guides for Hyprland on FreeBSD, hence the feature request ... many Thanks

**Comment by JaKooLit** [comment]
sorry I have no experience with BSD so I cant
