### ISSUE TITLE
[Bug]: nwg-look does not compile

### ISSUE THREAD

**Issue by bmentink** [JaKooLit/Fedora-Hyprland#103]
nwg-look did not compile on mac apple m1, running Fedora remix, I will post details soon when back on the machine.
From memory the minimum go language provided by Fedora was too old .. go1.21 

I am following the tutorial below.
[https://www.youtube.com/watch?v=Nfm3oyJx_Hk](url)

**Comment by bmentink** [comment]
Update: Oops did not read the instructions correctly .... and it was marked important  :)
I set the go version to one that works and re-ran the install script ... works fine now.

One thing I noticed is that only one dark theme is actually dark. Adromeda-dark is the only one.
The other dark themes are light ...

**Comment by JaKooLit** [comment]
https://github.com/JaKooLit/Hyprland-Dots/wiki/FAQ#%EF%B8%8F-themes-are-broken-when-changing-dark-light-or-no-themes-after-installing-even-opted-to-install-gtk-themes


by default I have only set to install 1 dark and 1 light

the faq above should give you an idea how to set your own theme

**Comment by bmentink** [comment]
Many Thanks

**Comment by bmentink** [comment]
By the way, I notice that in waybar I have 5 numbers that I presume switch workspaces, however they do nothing. What can i check to fix, thanks..

**Comment by JaKooLit** [comment]
those are persistent workspaces

edit ~/.config/waybar/modules if you dont like it

https://github.com/Alexays/Waybar/wiki/Module:-Workspaces#persistent-workspaces

**Comment by bmentink** [comment]
Understand they are persistent. And yes I like. What I don't understand is why when you click on them they do nothing, no change to workspace, the hot keys work ok ... is this a bug

**Comment by JaKooLit** [comment]
when you click the workspaces that one was selected?

you probably think that workspaces didnt change because no animation if no apps opened on that workspaces 

but when you click that workspace, you switched to that workspaces

**Comment by bmentink** [comment]
No nothing happened. I have different apps in each workspace, so can tell if the workspace is changed. Why you not believe me?

**Comment by JaKooLit** [comment]
its not that I dont believe you

because I dont have issue on my fedora

suggest you file a report to waybar github page

**Comment by bmentink** [comment]
I am on Fedora remix for mac M1, would that make a difference?

**Comment by JaKooLit** [comment]
sorry I have no idea. I dont have apple stuff

**Comment by bmentink** [comment]
Hi,
I fixed all my issues, by upgrading Fedora from 39 to 40. So it may be that
39 was having issues with your latest version? Just reporting this to help
you out ..
Cheers
