### ISSUE TITLE
[Bug]: Short description of the issue

### ISSUE THREAD

**Issue by GageHoweTamu** [JaKooLit/Fedora-Hyprland#104]
### Description

Error message: "Config error in file /home/user/.config/hypr/hyprland.conf at line 108: config opttion <master:new_is_master> does not exist."

### Steps to Reproduce

Install Fedora from scratch, then run the script. Do NOT remove Gnome dependencies etc when prompted.

### Expected Behavior

Correct installation

### Actual Behavior

Error message: "Config error in file /home/user/.config/hypr/hyprland.conf at line 108: config opttion <master:new_is_master> does not exist."

### Environment

Lenovo Legion Pro 7 with Nvidia 4080

### Additional Information

[Add any other information about the problem here. For example, you might include the error message, any recent changes that you made to the project, or any other relevant details.]

### show output of `inxi -CGIsSMnr` install package `inxi` if not exist

Can't access terminal

**Comment by JaKooLit** [comment]
when did you install?

**Comment by GageHoweTamu** [comment]
> when did you install?

Yesterday. I tried a few days ago with the "delete gnome xyz implementations" option on, which bricked the installation.

**Comment by JaKooLit** [comment]
strange. I released a fix 4 days ago

anyway,

to correct that new master error
SUPER E
choose User-Settings
about line 20 or start from line 20,
master {
       comment (#) or delete line new_is_master=1
       change to new_status=master
}

https://github.com/JaKooLit/Hyprland-Dots/blob/main/config%2Fhypr%2FUserConfigs%2FUserSettings.conf#L21-L22

#new_is_master=1 # comment this when Hyprland release a new version or you are running the git version
  new_status=master # hyprland upstream or git version (next release maybe v0.41-2 or v0.42)





option 2, update your dots
https://github.com/JaKooLit/Hyprland-Dots/wiki/Install_&_Update
