### ISSUE TITLE
Strange behavior with tmux, sessions

### ISSUE THREAD

**Issue by mr-scrpt** [JaKooLit/Fedora-Hyprland#116]
### Description
I've been using your `Fedora Linux` build for about half a year now, during which time I've tried several versions with clean installs.

My problem is that I use `tmux ` - it allows me to create sessions where I have the terminals I want open, in the directories I want. Let me give an example to make it clearer - I have several working projects, in all of them I use neovim to edit code, everywhere there should be a terminal open to start the server, a terminal for the file manager, in some projects there may be a terminal to work with the database, somewhere to add a docker, etc. In order not to have to run all this every time the system starts, `tmux` has a plugin `tmux-resurrect `and `tmux-continuum` which save these sessions and restore them on system startup, I just need to write `tmux attach` in the terminal and my `tmux` will start in the state it was in before the computer restarted - all the projects I need and the terminals I need in the tmux panels will be open. All this works great on `macos`, before that I worked on `ubuntu` and `arch linux`, `manjaro` and it all worked there too.

But in your environment I observe very strange behavior - sometimes everything works as it should - more or less stable sessions are restored if you logout from the system, then `tmux attach` works as it should. But this doesn't always happen either. I use two monitors - one built into the laptop, and the other external - trying to find patterns, I came to the point where I tried logging in from one or the second monitor and it seems that if I wait for the second monitor to load (it happens about 5 seconds after the image has already appeared on the laptop screen) and logout from it, then the tmux session is restored correctly - but maybe it's not related, but just a coincidence or it happens because I just don't log in immediately, but wait (at this moment there are probably some background processes that affect the work), maybe there is some kind of `race conditions`.

If I completely reboot my computer, the session is never restored. But about 5 months ago when I last installed the system and your environment, at that time it was still Fedora 39 and one of the previous versions of your environment, even after rebooting the computer the sessions sometimes recovered and at that time it seemed to me that this was due to `pyprland` which, as I understand it, pre-starts the `ktitty terminal`

And I just don't understand how I could debuging this and what exactly it is related to. Maybe the terminals are pre-launching from the wrong users and something gets lost at that point, maybe it has to do with environment variables. Perhaps someone has encountered this or knows in principle what it could be related to? 

Translated with DeepL.com (free version)

### Steps to Reproduce

1. Installed Fedora
2. Ran 
```
git clone --depth=1 https://github.com/JaKooLit/Fedora-Hyprland.git ~/Fedora-Hyprland
cd ~/Fedora-Hyprland
chmod +x install.sh
./install.sh
```
3. Install `sudo dnf install tmux`
4. Install [TPM](https://github.com/tmux-plugins/tpm)
5. Install from tmux config plugins 
```
set -g @plugin 'tmux-plugins/tmux-resurrect' # persist tmux sessions after computer restart
set -g @plugin 'tmux-plugins/tmux-continuum' # automatically saves sessions for you every 15 minutes
```
 

### Expected Behavior

 Sessions should be restored after rebooting the computer by the command ` tmux attach`

### Actual Behavior
Not restored

### Screenshots
![image](https://github.com/user-attachments/assets/b0680c16-84bd-4dd2-95c8-5cecc612fe5c)

### Environment

- Fedora 40
- Linux mrstation 6.9.9-403.asahi.fc40.aarch64+16k #1 SMP PREEMPT_DYNAMIC Sat Jul 13 23:35:21 UTC 2024 aarch64 GNU/Linux
- Hyprland, built from branch  at commit 918d8340afd652b011b937d29d5eea0be08467f5  (flake.lock: update).
Date: Tue Jun 25 12:06:02 2024
Tag: v0.41.2, commits: 4886

flags: (if any)
- On The Main Hardware - On Macbook Pro M1 through [asahi linux](https://asahilinux.org/)

### show output of `inxi -CGIsSMnr` install package `inxi` if not exist
show output here
```
System:
  Host: mrstation Kernel: 6.9.9-403.asahi.fc40.aarch64+16k arch: aarch64
    bits: 64
  Desktop: Hyprland v: 0.41.2 Distro: Fedora Linux Asahi Remix 40 (KDE
    Plasma)
Machine:
  Type: ARM System: Apple MacBook Pro (16-inch, M1 Pro, 2021) details: N/A
    serial: DF79PJF25X
CPU:
  Info: quad core model: N/A variant-1: firestorm variant-2: icestorm bits: 64
    type: MT MCP cache: L2: 28 MiB
  Speed (MHz): avg: 1574 min/max: 600/2064:3228 cores: 1: 600 2: 600 3: 600
    4: 600 5: 600 6: 600 7: 3036 8: 3036 9: 3036 10: 3036
Graphics:
  Device-1: agx-t6000 driver: asahi v: kernel
  Device-2: display-subsystem driver: apple_drm v: N/A
  Display: wayland server: Xwayland v: 24.1.1 compositor: Hyprland v: 0.41.2
    driver: N/A resolution: 1: 3200x1800 2: 1728x1080
  API: EGL v: 1.5 drivers: asahi,swrast
    platforms: wayland,x11,surfaceless,device
  API: OpenGL v: 4.6 compat-v: 4.5 vendor: mesa v: 24.2.0-asahi20240725
    renderer: Apple M1 Pro (G13S C0)
  API: Vulkan v: 1.3.283 drivers: N/A surfaces: xcb,xlib,wayland
Network:
  Device-1: Broadcom BCM4387 802.11ax Dual Band Wireless LAN driver: brcmfmac
  IF: wlp1s0f0 state: up mac: 2e:94:ee:5d:0c:ff
  Device-2: Broadcom BRCM4387 Bluetooth driver: hci_bcm4377
  IF-ID-1: br-631df4e4627c state: up speed: 10000 Mbps duplex: unknown
    mac: 02:42:31:e4:c0:2b
  IF-ID-2: docker0 state: down mac: 02:42:5f:d3:68:5f
  IF-ID-3: veth0568955 state: up speed: 10000 Mbps duplex: full
    mac: aa:3c:ff:7c:c5:70
Sensors:
  Src: lm-sensors+/sys Message: No sensor data found using /sys/class/hwmon
    or lm-sensors.
Repos:
  No active dnf repos in: /etc/dnf/dnf.conf
  Active yum repos in: /etc/yum.repos.d/_copr:copr.fedorainfracloud.org:atim:lazygit.repo
    1: copr:copr.fedorainfracloud.org:atim:lazygit ~ https://download.copr.fedorainfracloud.org/results/atim/lazygit/fedora-$releasever-$basearch/
  Active yum repos in: /etc/yum.repos.d/_copr:copr.fedorainfracloud.org:erikreider:SwayNotificationCenter.repo
    1: copr:copr.fedorainfracloud.org:erikreider:SwayNotificationCenter ~ https://download.copr.fedorainfracloud.org/results/erikreider/SwayNotificationCenter/fedora-$releasever-$basearch/
  Active yum repos in: /etc/yum.repos.d/_copr:copr.fedorainfracloud.org:solopasha:hyprland.repo
    1: copr:copr.fedorainfracloud.org:solopasha:hyprland ~ https://download.copr.fedorainfracloud.org/results/solopasha/hyprland/fedora-$releasever-$basearch/
  Active yum repos in: /etc/yum.repos.d/docker-ce.repo
    1: docker-ce-stable ~ https://download.docker.com/linux/fedora/$releasever/$basearch/stable
  Active yum repos in: /etc/yum.repos.d/fedora-asahi-remix-hotfixes.repo
    1: fedora-asahi-remix-hotfixes ~ https://fedora-asahi-remix.org/repos/hotfixes/$releasever/
  Active yum repos in: /etc/yum.repos.d/fedora-cisco-openh264.repo
    1: fedora-cisco-openh264 ~ https://mirrors.fedoraproject.org/metalink?repo=fedora-cisco-openh264-$releasever&arch=$basearch
  No active yum repos in: /etc/yum.repos.d/fedora-updates-testing.repo
  Active yum repos in: /etc/yum.repos.d/fedora-updates.repo
    1: updates ~ https://mirrors.fedoraproject.org/metalink?repo=updates-released-f$releasever&arch=$basearch
  Active yum repos in: /etc/yum.repos.d/fedora.repo
    1: fedora ~ https://mirrors.fedoraproject.org/metalink?repo=fedora-$releasever&arch=$basearch
  Active yum repos in: /etc/yum.repos.d/group_asahi-fedora-remix-branding.repo
    1: copr:copr.fedorainfracloud.org:group_asahi:fedora-remix-branding ~ https://download.copr.fedorainfracloud.org/results/@asahi/fedora-remix-branding/fedora-$releasever-$basearch/
  Active yum repos in: /etc/yum.repos.d/group_asahi-fedora-remix-scripts.repo
    1: copr:copr.fedorainfracloud.org:group_asahi:fedora-remix-scripts ~ https://download.copr.fedorainfracloud.org/results/@asahi/fedora-remix-scripts/fedora-$releasever-$basearch/
  Active yum repos in: /etc/yum.repos.d/group_asahi-flatpak.repo
    1: copr:copr.fedorainfracloud.org:group_asahi:flatpak ~ https://download.copr.fedorainfracloud.org/results/@asahi/flatpak/fedora-$releasever-$basearch/
  Active yum repos in: /etc/yum.repos.d/group_asahi-kernel.repo
    1: copr:copr.fedorainfracloud.org:group_asahi:kernel ~ https://download.copr.fedorainfracloud.org/results/@asahi/kernel/fedora-$releasever-$basearch/
  Active yum repos in: /etc/yum.repos.d/group_asahi-mesa.repo
    1: copr:copr.fedorainfracloud.org:group_asahi:mesa ~ https://download.copr.fedorainfracloud.org/results/@asahi/mesa/fedora-$releasever-$basearch/
  Active yum repos in: /etc/yum.repos.d/group_asahi-u-boot.repo
    1: copr:copr.fedorainfracloud.org:group_asahi:u-boot ~ https://download.copr.fedorainfracloud.org/results/@asahi/u-boot/fedora-$releasever-$basearch/
  No active yum repos in: /etc/yum.repos.d/rpmfusion-free-updates-testing.repo
  Active yum repos in: /etc/yum.repos.d/rpmfusion-free-updates.repo
    1: rpmfusion-free-updates ~ https://mirrors.rpmfusion.org/metalink?repo=free-fedora-updates-released-$releasever&arch=$basearch
  Active yum repos in: /etc/yum.repos.d/rpmfusion-free.repo
    1: rpmfusion-free ~ https://mirrors.rpmfusion.org/metalink?repo=free-fedora-$releasever&arch=$basearch
  No active yum repos in: /etc/yum.repos.d/rpmfusion-nonfree-nvidia-driver.repo
  No active yum repos in: /etc/yum.repos.d/rpmfusion-nonfree-updates-testing.repo
  Active yum repos in: /etc/yum.repos.d/rpmfusion-nonfree-updates.repo
    1: rpmfusion-nonfree-updates ~ https://mirrors.rpmfusion.org/metalink?repo=nonfree-fedora-updates-released-$releasever&arch=$basearch
  Active yum repos in: /etc/yum.repos.d/rpmfusion-nonfree.repo
    1: rpmfusion-nonfree ~ https://mirrors.rpmfusion.org/metalink?repo=nonfree-fedora-$releasever&arch=$basearch
Info:
  Memory: total: 16 GiB note: est. available: 15.01 GiB used: 8.47 GiB (56.5%)
  Processes: 337 Uptime: 42m Shell: fish inxi: 3.3.34

```

**Comment by JaKooLit** [comment]
closing as no more reply from op
