### ISSUE TITLE
[Bug]: hp wireless mouse not working

### ISSUE THREAD

**Issue by chendjou237** [JaKooLit/Fedora-Hyprland#118]
### Description
My hp wireless mouse does not work. When installing hyperland I selected "no" for configure Bluetooth. Since then I try using hp-setup but it's not detecting the mouse 
### Steps to Reproduce

1. Install hyperland 
2. Select "no" for configuring Bluetooth during setup 
3. Plugged in the mouse head 

### Expected Behavior

I expect the mouse to work out of the box or even have appropriate driver to install to make it work 

### Actual Behavior

Mouse don't work and even hp-setup can't solve the problem 

### Environment

- Linux Distro: Fedora 40

### Additional Information

**Comment by JaKooLit** [comment]
is your hp mouse bluetooth?

bluetooth installation is to only install bluetooth packages and NOT disable anything

**Comment by chendjou237** [comment]
> is your hp mouse bluetooth?
> 
> bluetooth installation is to only install bluetooth packages and start bluetooth and NOT disable anything

Yes my hp mouse is bluetooth, I am not able to access bluetooth device. I don't know if i should just reinstall the setup of hyperland because of that single "enable bluetooth configuration" that i said no at the start

**Comment by JaKooLit** [comment]
https://github.com/JaKooLit/Fedora-Hyprland?tab=readme-ov-file#-proper-way-to-re-installing-a-particular-script-from-install-scripts-directory


ran the bluetooh.sh as per the readme
