### ISSUE TITLE
[Custom]: Double binding for $mainMod SHIFT, tab correct?

### ISSUE THREAD

**Issue by devax** [JaKooLit/Fedora-Hyprland#121]
### Description

I'm new to Hyprland and am trying out different workflows. This is Fedora 40, current version of your scripts, Hyprland 0.42.0.

I'm a bit confused with the default configured behavior for groups. 
In `.config/hypr/configs/Keybinds.conf`, there are two entries for `$mainMod SHIFT, tab`:
```bash
bind = $mainMod SHIFT, tab, changegroupactive  #change focus to another window
# and
bind = $mainMod SHIFT, tab, workspace, m-1
```
So when I create a group ($mainMod, G) and then try to toggle between the group windows by pressing $mainMod SHIFT, tab, this will not only toggle the group windows but also change the current workspace.

Is this intended default configuration or am I missing something?

Hope this question makes somewhat sense.

And by the way: This is such a great project, thank you so much for it!

### Steps to Reproduce (if applicable)

1. Have windows on multiple workspaces open.
2. On one workspace, create a group with multiple windows
3. Use $mainMod SHIFT, tab to toggle between the windows in the group

### Expected Behavior

Workspace should change, only windows in groups should toggle

### Actual Behavior

Workspace changes

### Proposed Solution (if applicable)

The default keybindings should be adjusted, so that $mainMod SHIFT, tab is only bound to one of the two actions.

**Comment by JaKooLit** [comment]
Thanks for this..

Obviously its a mistake :)

I dont use group mode much so I didnt really notice... Whats the best keybind for change groupactive?

SUPER CTRL TAB is ok?

**Comment by devax** [comment]
SUPER CTRL TAB is a very good suggestion, thank you! Let me know if you want me to create a PR for this.

**Comment by JaKooLit** [comment]
https://github.com/JaKooLit/Hyprland-Dots/commit/a5fbf7856217a60f6c55fe679baf4a9891b01d8e

Thanks bro.
