### ISSUE TITLE
your hyprlock design had a issue for long time

### ISSUE THREAD

**Issue by Maddy6914** [JaKooLit/Fedora-Hyprland#125]
### Before submitting report

[Kindly review the log files in Install-Logs directory. Some apps may have not installed properly.]

### Description

your hyprlock design had a issue for long time i have made a new alignment in there which looks better than the past ,kindly see that design ,and i attach that below ,one more thing i am new to github so sorry for the entry in the wrong place ,i dont know where to place this issue that's y i made here.
[hyprlock_modified.txt](https://github.com/user-attachments/files/16848550/hyprlock_modified.txt)
![hyprlock_correction_img](https://github.com/user-attachments/assets/bc150c66-b2ed-4329-8492-6ad8d6db541e)

### Steps to Reproduce (if applicable)

1. [First Step]
2. [Second Step]
3. [and so on...]

### Expected Behavior

[What did you expect to happen?]

### Actual Behavior

[What actually happened?]

### Screenshots (if applicable)

[If applicable, add screenshots to help explain your problem.]

### Proposed Solution (if applicable)

[If you have a specific solution in mind, describe it here. If not, you can skip this section.]

### Additional Information

[Add any other information about the issue or request here. For example, you might include links to similar features in other projects, or screenshots or diagrams to help explain your idea.]

### show output of `inxi -CGIsSMnr` install package `inxi` if not exist
show output here
```


```

**Comment by JaKooLit** [comment]
whats your screen resolution?

**Comment by JaKooLit** [comment]
https://github.com/JaKooLit/Hyprland-Dots/blob/main/config/hypr/hyprlock-1080p.conf

you probably just copy it without changing anything or didnt ran the copy.sh or when you were prompted, you chose >1440 resolution

the attached config which you attached is for 1440p. You can see the header

on the link above is for <=1080p
