### ISSUE TITLE
A quick question

### ISSUE THREAD

**Issue by EdgyGuy19** [JaKooLit/Fedora-Hyprland#126]
I just have a quick question. How can I remove all files that have to do with this installation and hyprland?

**Comment by JaKooLit** [comment]
wallpapers - ~/Pictures/wallpapers

configs - ~/.config/hypr, btop, waybar, rofi etc etc


there is an experimental uninstaller made by other user. I do not guarantee it...

as I mentioned on my readme
https://github.com/JaKooLit/Fedora-Hyprland?tab=readme-ov-file#-announcement-


I did not include official uninstaller
