### ISSUE TITLE
sddm-simple doesn't work

### ISSUE THREAD

**Issue by EdgyGuy19** [JaKooLit/Fedora-Hyprland#128]
I recently reinstalled hyprland on my laptop and encountered this problem with simple-sddm. Did same thing on my PC, by everything works there. it says the qtgraphicaleffects is not installed whet it is installed
![photo_2024-09-05_15-31-39](https://github.com/user-attachments/assets/6a2b4005-a51a-4667-b632-dd0c39b24131)

**Comment by JaKooLit** [comment]
ok thanks bro...

which fedora version you have?

**Comment by EdgyGuy19** [comment]
> ok thanks bro...
> 
> which fedora version you have?

Fedora 40

**Comment by JaKooLit** [comment]
> > ok thanks bro...
> > which fedora version you have?
> 
> Fedora 40

ok im firing up a new vm now to try out

**Comment by EdgyGuy19** [comment]
> > > ok thanks bro...
> > > which fedora version you have?
> > 
> > Fedora 40
> 
> ok im firing up a new vm now to try out

It's weird cause it works on my PC with same fedora version

**Comment by JaKooLit** [comment]
![swappy-20240908-003712](https://github.com/user-attachments/assets/cd300e7c-e82f-49ad-97ea-befb05d0ce4d)

just finish using the script.. sddm is fine

oh perhaps you use the simple-sddm1
https://github.com/JaKooLit/simple-sddm

where I have another simple-sddm which is qt6
https://github.com/JaKooLit/simple-sddm-2

but the script, it was set to simple-sddm-2

**Comment by EdgyGuy19** [comment]
> ![swappy-20240908-003712](https://github.com/user-attachments/assets/cd300e7c-e82f-49ad-97ea-befb05d0ce4d)
> 
> just finish using the script.. sddm is fine
> 
> oh perhaps you use the simple-sddm1
> https://github.com/JaKooLit/simple-sddm
> 
> where I have another simple-sddm which is qt6
> https://github.com/JaKooLit/simple-sddm-2
> 
> but the script, it was set to simple-sddm-2
> 

Ok, I will try it****

**Comment by JaKooLit** [comment]
does this fix the issue?

**Comment by EdgyGuy19** [comment]
nope, I will try to reinstall the hyprland installation config again

**Comment by EdgyGuy19** [comment]
yep, still does not work

**Comment by JaKooLit** [comment]
well I dont really know what to say

since Ive tried on a newly installed fedora minimal usinh fedora everything without DE

**Comment by JaKooLit** [comment]
can you show me output of

cat /etc/sddm.conf.d/theme.conf.user

**Comment by EdgyGuy19** [comment]
here is ls usr/share/sddm/themes/

elarun  maldives  maya  simple-sddm

but I dont have the first config file

**Comment by JaKooLit** [comment]
can you do this.. if you still have the Fedora-Hyprland
cd into it then git stash && git pull
./install-scripts/sddm.sh


if not download Fedora-Hyprland using git
cd into it
./install-scripts/sddm.sh

**Comment by EdgyGuy19** [comment]
> can you do this.. if you still have the Fedora-Hyprland cd into it then git stash && git pull ./install-scripts/sddm.sh
> 
> if not download Fedora-Hyprland using git cd into it ./install-scripts/sddm.sh

done

**Comment by JaKooLit** [comment]
no idea ...

it works on my test VM so not sure what happen to yours.. I didnt even adjust anything

**Comment by EdgyGuy19** [comment]
> no idea ...
> 
> it works on my test VM so not sure what happen to yours.. I didnt even adjust anything

weird shit. but if it works, it works🤷🏼‍♂️
