### ISSUE TITLE
[Bug]: Fedora 41 beta   NVIM errors phyton 3 doesn't meet min requirements 

### ISSUE THREAD

**Issue by dwilliam62** [JaKooLit/Fedora-Hyprland#134]
### Before submitting report

[Kindly review the log files in Install-Logs directory. Some apps may have not installed properly.]

### Description

[Provide a clear and concise description of the bug.]

### Steps to Reproduce

Installed Fedora F41 branch of Fedora-Hyprland 
rebooted
Started NVIM
node2js wasn't installed added that 
got Mason failed to build errors

![Screenshot_17-Sep_17-09-34_2767](https://github.com/user-attachments/assets/225bf685-27d0-4f51-876c-3e6f0b8ce75d)

MasonLogs 

![Screenshot_17-Sep_17-10-41_25849](https://github.com/user-attachments/assets/8764cac8-a088-4c04-a8ec-d1c9a6573368)

### Expected Behavior

[What did you expect to happen?]

### Actual Behavior

Error cmake failed to build 

 

### Environment

[Please add any other relevant information about the bug and remove the unnecessary lines.]

Fedora 41 beta

**Comment by dwilliam62** [comment]
Solution:   Install  python3.12-devel     I don't see a -devel for 3.13.   But this resolved the error.  Need to add to your package list for Fedora 41

**Comment by JaKooLit** [comment]
Thanks bro.

Decided not to include the neovim config anymore in the installation (copy) of dotfiles.

This is because without config, wont face any issues.

Most neovim users have their own neovim configs anyway.

I dont use neovim myself as Im happy with vscodium

**Comment by dwilliam62** [comment]
OK  Just do one thing.   Fork NVIM to a repo so i can easily be added
 It's a nice config I like it and would like to see it preserved

**Comment by JaKooLit** [comment]
no need. nvim still there but it will not be copied.

I modified the copy.sh to choose which to copy or not
