### ISSUE TITLE
[Bug]: Google Chrome always opening in the second workspace ignoring the current one

### ISSUE THREAD

**Issue by chahidanas** [JaKooLit/Fedora-Hyprland#141]
### Description

Whenever I try to open google chrome it always take me to the second workspace, I tried to close chrome in a different workspace before rebooting, still same issue.
Does not happen with Brave or Firefox

### Steps to Reproduce

1. Download google chrome from the second workspace
2. Open it in the second workspace for the first time
3. Reboot
4. Try to open Chrome in any other workspace

### Expected Behavior

Ghrome opening in the current workspace

### Actual Behavior

Chrome always open in the second workspace ignoring the current one, even the special workspace (mainMode + U workspace)

### Environment

- Linux Distro: Fedora 40 Workstation
- Linux Version: Linux  6.11.3-200.fc40.x86_64 #1 SMP PREEMPT_DYNAMIC x86_64 GNU/Linux
- Hyprland Version, output of `hyprctl version`: v0.44.1
- Installation Environment: On The Main Hardware

**Comment by JaKooLit** [comment]
https://github.com/JaKooLit/Hyprland-Dots/wiki/FAQ#-some-packages-are-opening-on-a-specific-workspaces

**Comment by chahidanas** [comment]
Thank you for the quick reply, I somehow completly missed that part, even tho I have a new bug, and this time I'm 89% sure I didn't missed a part about it in the faq
