### ISSUE TITLE
[Bug]: Short description of the issue

### ISSUE THREAD

**Issue by XpPlayz** [JaKooLit/Fedora-Hyprland#146]
### Description

I just installed hyperland using the script, and as soon as I booted up into the desktop the wallpaper is black and when I try to use the wallpaper menu to change it, it does not work and remains black.

### Steps to Reproduce

1. Log in to system (hyperland)
2. view desktop
3. attempt to change wallpaper using the wallpaper manager

### Expected Behavior
I expected the wallpaper to change when using the wallpaper manager

### Actual Behavior
Wallpaper DID NOT change after using wallpaper manager and I am stuck with an empty black wallpaper

### Screenshots

![Screenshot_29-Oct_00-50-43_29432](https://github.com/user-attachments/assets/eebc5747-b853-42fd-8422-8ec0570f8961)

### Environment

- Linux Distro: Fedora Linux 40 Workstation
- Linux Version: Linux home 6.11.4-201.fc40.x86_64 #1 SMP PREEMPT_DYNAMIC Sun Oct 20 15:04:22 UTC 2024 x86_64 GNU/Linux
- Hyprland Version: v0.44.1
- Installation Environment: Main Hardware
- Other info: Laptop, 1920x1080 Intel Graphics

**Comment by JaKooLit** [comment]
swww may not be installed

re-running the install.sh should fix most issue

was there no error message after installation?
