### ISSUE TITLE
Encountering a strange error message 

### ISSUE THREAD

**Issue by digvijayizing** [JaKooLit/Fedora-Hyprland#147]
i just logged into hyprland after a month i was using gnome for a while and then suddenly i see this strange error message on the top of the screen after logging in 
![swappy-20241029-123453](https://github.com/user-attachments/assets/a10f6379-ca67-41a1-821c-ef129bd2edf0)

**Comment by JaKooLit** [comment]
https://github.com/JaKooLit/Hyprland-Dots/wiki/Install_&_Update

kindly update your dots
