### ISSUE TITLE
Hello, I installed hyprland in fedora linux 41, and it has crashed problems

### ISSUE THREAD

**Issue by dani0221** [JaKooLit/Fedora-Hyprland#152]
I attach the problem in a file, which describes the bug
[hyprlandCrashReport4647.txt](https://github.com/user-attachments/files/17724903/hyprlandCrashReport4647.txt)

**Comment by JaKooLit** [comment]
state what happened here. the crash report only helpful to hyprland team but not to me.

Kindly follow the template when reporting issue

**Comment by dani0221** [comment]
I understand, this is the problem : 
Welcome to Hyprland!
[LOG] Instance Signature: a425fbebe4cf4238e48a42f724ef2208959d66cf_1731517442_1454640104
[LOG] Runtime directory: /run/user/1000/hypr/a425fbebe4cf4238e48a42f724ef2208959d66cf_1731517442_1454640104
[LOG] Hyprland PID: 4027
[LOG] ===== SYSTEM INFO: =====
[LOG] System name: Linux
[LOG] Node name: fedora
[LOG] Release: 6.11.7-300.fc41.x86_64
[LOG] Version: #1 SMP PREEMPT_DYNAMIC Fri Nov  8 19:23:10 UTC 2024


[LOG] GPU information:
04:00.0 VGA compatible controller [0300]: Advanced Micro Devices, Inc. [AMD/ATI] Picasso/Raven 2 [Radeon Vega Series / Radeon Vega Mobile Series] [1002:15d8] (rev c2) (prog-if 00 [VGA controller])


[LOG] os-release:
NAME="Fedora Linux"
VERSION="41 (Workstation Edition)"
RELEASE_TYPE=stable
ID=fedora
VERSION_ID=41
VERSION_CODENAME=""
PLATFORM_ID="platform:f41"
PRETTY_NAME="Fedora Linux 41 (Workstation Edition)"
ANSI_COLOR="0;38;2;60;110;180"
LOGO=fedora-logo-icon
CPE_NAME="cpe:/o:fedoraproject:fedora:41"
DEFAULT_HOSTNAME="fedora"
HOME_URL="https://fedoraproject.org/"
DOCUMENTATION_URL="https://docs.fedoraproject.org/en-US/fedora/f41/system-administrators-guide/"
SUPPORT_URL="https://ask.fedoraproject.org/"
BUG_REPORT_URL="https://bugzilla.redhat.com/"
REDHAT_BUGZILLA_PRODUCT="Fedora"
REDHAT_BUGZILLA_PRODUCT_VERSION=41
REDHAT_SUPPORT_PRODUCT="Fedora"
REDHAT_SUPPORT_PRODUCT_VERSION=41
SUPPORT_END=2025-12-15
VARIANT="Workstation Edition"
VARIANT_ID=workstation

[LOG] ========================



[INFO] If you are crashing, or encounter any bugs, please consult https://wiki.hyprland.org/Crashes-and-Bugs/


[LOG] 
Current splash: Read the wiki.


[LOG] Old rlimit: soft -> 524288, hard -> 524288
[LOG] New rlimit: soft -> 524288, hard -> 524288
[LOG] Creating the EventLoopManager!
[LOG] Creating the HookSystem!
[LOG] Creating the KeybindManager!
[LOG] Creating the AnimationManager!
[LOG] Created a bezier curve, baked 255 points, mem usage: 4.08kB, time to bake: 69.96µs. Estimated average calc time: 0.09µs.
[LOG] Creating the ConfigManager!
[LOG] Created a bezier curve, baked 255 points, mem usage: 4.08kB, time to bake: 40.98µs. Estimated average calc time: 0.08µs.
[LOG] Using config: /home/angel-dev/.config/hypr/hyprland.conf
[INFO] !!!!HEY YOU, YES YOU!!!!: further logs to stdout / logfile are disabled by default. BEFORE SENDING THIS LOG, ENABLE THEM. Use debug:disable_logs = false to do so: https://wiki.hyprland.org/Configuring/Variables/#debug
[LOG] Creating the CHyprError!
[LOG] Creating the LayoutManager!
[LOG] Creating the TokenManager!
[LOG] [hookSystem] New hook event registered: preConfigReload
[LOG] Created a bezier curve, baked 255 points, mem usage: 4.08kB, time to bake: 37.23µs. Estimated average calc time: 0.07µs.
[LOG] Using config: /home/angel-dev/.config/hypr/hyprland.conf
[LOG] Created a bezier curve, baked 255 points, mem usage: 4.08kB, time to bake: 18.30µs. Estimated average calc time: 0.05µs.
[LOG] Created a bezier curve, baked 255 points, mem usage: 4.08kB, time to bake: 15.07µs. Estimated average calc time: 0.04µs.
[LOG] Created a bezier curve, baked 255 points, mem usage: 4.08kB, time to bake: 26.20µs. Estimated average calc time: 0.07µs.
[LOG] Created a bezier curve, baked 255 points, mem usage: 4.08kB, time to bake: 27.15µs. Estimated average calc time: 0.04µs.
[LOG] Created a bezier curve, baked 255 points, mem usage: 4.08kB, time to bake: 28.17µs. Estimated average calc time: 0.04µs.
[LOG] Created a bezier curve, baked 255 points, mem usage: 4.08kB, time to bake: 28.01µs. Estimated average calc time: 0.07µs.
[LOG] Created a bezier curve, baked 255 points, mem usage: 4.08kB, time to bake: 26.91µs. Estimated average calc time: 0.04µs.
wl_registry#2: error 0: invalid version for global wl_seat (15): have 8, wanted 9
terminate called after throwing an instance of 'std::runtime_error'
  what():  CBackend::create() failed!
Hyprland has crashed :( Consult the crash report at /home/angel-dev/.cache/hyprland/hyprlandCrashReport4027.txt for more information.
[1]    4027 IOT instruction (core dumped)  Hyprland

**Comment by JaKooLit** [comment]
as I mentioned, this crash report is NOT helpful to me 

![Screenshot_20241113_150924_GitHub.jpg](https://github.com/user-attachments/assets/16e458eb-6fb3-4837-8d26-9a8b34a6312a)

this is the template I was talking about

complete accordingly..


what I am after is it just installed?

I need the report from inxi as well

Im closing this and submit a proper issue
