### ISSUE TITLE
Nobara 39 defaults to dnf5. Might need to retest the script.

### ISSUE THREAD

**Issue by SViN24** [JaKooLit/Fedora-Hyprland#17]
Nobara 39 defaults to dnf5 as the default dnf with dnf4 available for backwards compatibility.

Considering dnf5 is not one to one compatible with dnf4 there might be a need to test the script and see if there are any points which cause issues.

For example here are my log files.
[logfiles.tar.gz](https://github.com/JaKooLit/Fedora-Hyprland/files/13776104/install-27-082.tar.gz)

**Comment by JaKooLit** [comment]
thanks for the heads up.. Ill test later on


However, pls do take note that the script is designed for fedora 38 & 39. And distros that are based from it are only a plus.. if this script works

But, ill test, and if need to adjust something and fedora39 wont break, then I will implement

**Comment by SViN24** [comment]
Totally understandable but it might be a good idea to make it a requirement considering it will probably be the default in fedora 40 and it is already available in 39/38.
Could help with preparation

**Comment by JaKooLit** [comment]
https://fedoraproject.org/wiki/Changes/ReplaceDnfWithDnf5#Current_status

I wont adjust the script

too bad nobara decided to switch to dnf5 even their mother distro still not ready for it....
