### ISSUE TITLE
Install error with Go not able to find GTK

### ISSUE THREAD

**Issue by Yoproo20** [JaKooLit/Fedora-Hyprland#18]
Tried to install but GO isn't able to continue (it just becomes stuck) when it reaches to NWG build, logs don't show anything but here is the terminal output:

[NOTE] Installing go ...
Last metadata expiration check: 0:02:14 ago on Tue 02 Jan 2024 05:16:29 PM EST.
Package golang-1.20.12-1.fc38.x86_64 is already installed.
Dependencies resolved.
Nothing to do.
[ERROR] go failed to install :( , please check the install.log. You may need to install manually! Sorry I have tried :(
[OK] gtk3 is already installed. Skipping...
[OK] gtk3-devel is already installed. Skipping...
[OK] cairo-devel is already installed. Skipping...
[OK] glib-devel is already installed. Skipping...
[NOTE] Installing nwg-look
 nwg-look directory already exists. Updating...
No local changes to save
Already up to date.
go build -v -o bin/nwg-look .
github.com/gotk3/gotk3/gtk

**_at this point it won't do anything_**

I looked and I get a 404 at [github.com/gotk3/gotk3/gtk](github.com/gotk3/gotk3/gtk) so that could explain it, any ideas on a fix?

**Comment by JaKooLit** [comment]
you dont really need go since you already have golang....

can you do this

cd Fedora-Hyprland/nwg-look

sudo make install

show me

and also, inside Fedora-Hyprland folder, there is a Install-Logs folder

can you attach here install-(date&time)_nwg-look.log and install(date & time)_nwg-look2.log

**Comment by JaKooLit** [comment]
╭─ja at Fedora-G15 in ~/Fedora-Hyprland/nwg-look on main✔ 24-01-03 - 9:15:17
╰─⠠⠵ make build
go build -v -o bin/nwg-look .
╭─ja at Fedora-G15 in ~/Fedora-Hyprland/nwg-look on main✔ 24-01-03 - 9:15:20
╰─⠠⠵ sudo make install                    
[sudo] password for ja: 
mkdir -p /usr/share/nwg-look
mkdir -p /usr/share/nwg-look/langs
mkdir -p /usr/bin
mkdir -p /usr/share/applications
mkdir -p /usr/share/pixmaps
cp stuff/main.glade /usr/share/nwg-look/
cp langs/* /usr/share/nwg-look/langs/
cp stuff/nwg-look.desktop /usr/share/applications/
cp stuff/nwg-look.svg /usr/share/pixmaps/
cp bin/nwg-look /usr/bin
╭─ja at Fedora-G15 in ~/Fedora-Hyprland/nwg-look on main✔ 24-01-03 - 9:15:27
╰─⠠⠵ 

I just tried it...

**Comment by NavatejR** [comment]
How did you do it? Steps please? I also get stuck on the same I couldn't find anything useful:
These are the logs
[33m[NOTE](B[m Installing asusctl ...
Last metadata expiration check: 0:00:02 ago on Wed 15 May 2024 01:20:38 PM IST.
Last metadata expiration check: 0:00:02 ago on Wed 15 May 2024 01:20:38 PM IST.
Dependencies resolved.
Dependencies resolved.
==========================================================================================
 Package   Arch    Version      Repository                                            Size
==========================================================================================
Installing:
 asusctl   x86_64  6.0.7-3.fc40 copr:copr.fedorainfracloud.org:lukenukem:asus-linux  6.9 M

Transaction Summary
==========================================================================================
Install  1 Package

==========================================================================================
 Package   Arch    Version      Repository                                            Size
==========================================================================================
Installing:
 asusctl   x86_64  6.0.7-3.fc40 copr:copr.fedorainfracloud.org:lukenukem:asus-linux  6.9 M

Transaction Summary
==========================================================================================
Install  1 Package

Total download size: 6.9 M
Total download size: 6.9 M
Installed size: 19 M
Installed size: 19 M
Downloading Packages:
Downloading Packages:
asusctl-6.0.7-3.fc40.x86_64.rpm                 9.7 MB/s | 6.9 MB     00:00    
asusctl-6.0.7-3.fc40.x86_64.rpm                 9.7 MB/s | 6.9 MB     00:00    
--------------------------------------------------------------------------------
--------------------------------------------------------------------------------
Total                                           9.6 MB/s | 6.9 MB     00:00     
Total                                           9.6 MB/s | 6.9 MB     00:00     
Copr repo for asus-linux owned by lukenukem      11 kB/s | 1.0 kB     00:00    
Copr repo for asus-linux owned by lukenukem      11 kB/s | 1.0 kB     00:00    
Importing GPG key 0x0C881273:
 Userid     : "lukenukem_asus-linux (None) <lukenukem#asus-linux@copr.fedorahosted.org>"
 Fingerprint: 110A 7FBE ECDD 95C6 C9D2 057C 1622 BB1E 0C88 1273
 From       : https://download.copr.fedorainfracloud.org/results/lukenukem/asus-linux/pubkey.gpg
Importing GPG key 0x0C881273:
 Userid     : "lukenukem_asus-linux (None) <lukenukem#asus-linux@copr.fedorahosted.org>"
 Fingerprint: 110A 7FBE ECDD 95C6 C9D2 057C 1622 BB1E 0C88 1273
 From       : https://download.copr.fedorainfracloud.org/results/lukenukem/asus-linux/pubkey.gpg
Key imported successfully
Key imported successfully
Running transaction check
Running transaction check
Transaction check succeeded.
Transaction check succeeded.
Running transaction test
Running transaction test
Transaction test succeeded.
Transaction test succeeded.
Running transaction
Running transaction
  Preparing        :                                                        1/1  Preparing        :                                                        1/1 
  Installing       : asusctl-6.0.7-3.fc40.x86_64                            1/1 
  Installing       : asusctl-6.0.7-3.fc40.x86_64                            1/1 
  Running scriptlet: asusctl-6.0.7-3.fc40.x86_64                            1/1 
  Running scriptlet: asusctl-6.0.7-3.fc40.x86_64                            1/1 

Installed:
  asusctl-6.0.7-3.fc40.x86_64                                                   

Complete!
 

Installed:
  asusctl-6.0.7-3.fc40.x86_64                                                   

Complete!
[1A[K[32m[OK](B[m asusctl was installed.
[33m[NOTE](B[m Installing supergfxctl ...
Last metadata expiration check: 0:00:10 ago on Wed 15 May 2024 01:20:38 PM IST.
Last metadata expiration check: 0:00:10 ago on Wed 15 May 2024 01:20:38 PM IST.
Dependencies resolved.
Dependencies resolved.
==============================================================================================
 Package       Arch    Version      Repository                                            Size
==============================================================================================
Installing:
 supergfxctl   x86_64  5.2.1-2.fc40 copr:copr.fedorainfracloud.org:lukenukem:asus-linux  1.6 M

Transaction Summary
==============================================================================================
Install  1 Package

==============================================================================================
 Package       Arch    Version      Repository                                            Size
==============================================================================================
Installing:
 supergfxctl   x86_64  5.2.1-2.fc40 copr:copr.fedorainfracloud.org:lukenukem:asus-linux  1.6 M

Transaction Summary
==============================================================================================
Install  1 Package

Total download size: 1.6 M
Total download size: 1.6 M
Installed size: 6.5 M
Installed size: 6.5 M
Downloading Packages:
Downloading Packages:
supergfxctl-5.2.1-2.fc40.x86_64.rpm             5.5 MB/s | 1.6 MB     00:00    
supergfxctl-5.2.1-2.fc40.x86_64.rpm             5.5 MB/s | 1.6 MB     00:00    
--------------------------------------------------------------------------------
--------------------------------------------------------------------------------
Total                                           5.5 MB/s | 1.6 MB     00:00     
Total                                           5.5 MB/s | 1.6 MB     00:00     
Running transaction check
Running transaction check
Transaction check succeeded.
Transaction check succeeded.
Running transaction test
Running transaction test
Transaction test succeeded.
Transaction test succeeded.
Running transaction
Running transaction
  Preparing        :                                                        1/1  Preparing        :                                                        1/1 
  Installing       : supergfxctl-5.2.1-2.fc40.x86_64                        1/1 
  Installing       : supergfxctl-5.2.1-2.fc40.x86_64                        1/1 
  Running scriptlet: supergfxctl-5.2.1-2.fc40.x86_64                        1/1 
  Running scriptlet: supergfxctl-5.2.1-2.fc40.x86_64                        1/1 

Installed:
  supergfxctl-5.2.1-2.fc40.x86_64                                               

Complete!
 

Installed:
  supergfxctl-5.2.1-2.fc40.x86_64                                               

Complete!
[1A[K[32m[OK](B[m supergfxctl was installed.
[33m[NOTE](B[m Installing asusctl-rog-gui ...
Last metadata expiration check: 0:00:15 ago on Wed 15 May 2024 01:20:38 PM IST.
Last metadata expiration check: 0:00:15 ago on Wed 15 May 2024 01:20:38 PM IST.
Dependencies resolved.
Dependencies resolved.
==================================================================================================
 Package           Arch    Version      Repository                                            Size
==================================================================================================
Installing:
 asusctl-rog-gui   x86_64  6.0.7-3.fc40 copr:copr.fedorainfracloud.org:lukenukem:asus-linux  4.0 M

Transaction Summary
==================================================================================================
Install  1 Package

==================================================================================================
 Package           Arch    Version      Repository                                            Size
==================================================================================================
Installing:
 asusctl-rog-gui   x86_64  6.0.7-3.fc40 copr:copr.fedorainfracloud.org:lukenukem:asus-linux  4.0 M

Transaction Summary
==================================================================================================
Install  1 Package

Total download size: 4.0 M
Total download size: 4.0 M
Installed size: 15 M
Installed size: 15 M
Downloading Packages:
Downloading Packages:
asusctl-rog-gui-6.0.7-3.fc40.x86_64.rpm         9.8 MB/s | 4.0 MB     00:00    
asusctl-rog-gui-6.0.7-3.fc40.x86_64.rpm         9.8 MB/s | 4.0 MB     00:00    
--------------------------------------------------------------------------------
--------------------------------------------------------------------------------
Total                                           9.7 MB/s | 4.0 MB     00:00     
Total                                           9.7 MB/s | 4.0 MB     00:00     
Running transaction check
Running transaction check
Transaction check succeeded.
Transaction check succeeded.
Running transaction test
Running transaction test
Transaction test succeeded.
Transaction test succeeded.
Running transaction
Running transaction
  Preparing        :                                                        1/1  Preparing        :                                                        1/1 
  Installing       : asusctl-rog-gui-6.0.7-3.fc40.x86_64                    1/1 
  Installing       : asusctl-rog-gui-6.0.7-3.fc40.x86_64                    1/1 
  Running scriptlet: asusctl-rog-gui-6.0.7-3.fc40.x86_64                    1/1 
  Running scriptlet: asusctl-rog-gui-6.0.7-3.fc40.x86_64                    1/1 

Installed:
  asusctl-rog-gui-6.0.7-3.fc40.x86_64                                           

Complete!
 

Installed:
  asusctl-rog-gui-6.0.7-3.fc40.x86_64                                           

Complete!
[1A[K[32m[OK](B[m asusctl-rog-gui was installed.
Created symlink /etc/systemd/system/getty.target.wants/supergfxd.service → /usr/lib/systemd/system/supergfxd.service.
