### ISSUE TITLE
How to uninstall your dotfiles on fedora? 

### ISSUE THREAD

**Issue by orcbolg3612** [JaKooLit/Fedora-Hyprland#19]
I know this is hard and can't remove completely your dotfiles, can you show how to delete somes?

**Comment by JaKooLit** [comment]
![Screenshot_03-Jan_18-27-50_2737](https://github.com/JaKooLit/Fedora-Hyprland/assets/85185940/6e6a6965-07eb-412b-8a67-c8c14db926de)


First off, it is stated on Readme as if I add uninstall script, there maybe packages that are shared which is already installed before running this script. Which will possibly brick system


Uninstalling package is easy as sudo dnf remove <package>

and the packages that I have set to install are all in here

https://github.com/JaKooLit/Fedora-Hyprland/tree/main/install-scripts

dotfiles are all saved in ~/.config you can just delete those files + wallpapers, which is in ~/Pictures

for nwg-look go inside Fedora-Hyprland folder cd into nwg-look 
then sudo make uninstall
