### ISSUE TITLE
Getting an error right after agreeing to remove other XDG-desktop-portal-KDE implementations

### ISSUE THREAD

**Issue by pontoi** [JaKooLit/Fedora-Hyprland#22]
I have been trying to find why this error (install-scripts/zsh.sh: line 103: chsh: command not found [ERROR] Authentication failed. Please enter the correct password.) gets spammed after agreeing to remove XDG-desktop-portal-KDE implementations. Im intressted if anyone has an idea why this is occurring?

**Comment by JaKooLit** [comment]
attach here install logs

note: kde and gnome portals are not set to be removed since it is baked in plasma and gnome.

the chsh command not found because probably installation of util-linux package is not installed

again, cant say more unless install-logs are checked

**Comment by pontoi** [comment]
Here are the install logs before and after encountering the error. However, the errors do not appear in the last log. In the initial log, it was mentioned that sddm did not get installed. I attempted to install it, but got that it was already installed, so no luck there. Just say if you want more logs or just all and ill attach them

[install-12-215717_sddm.log](https://github.com/JaKooLit/Fedora-Hyprland/files/13923988/install-12-215717_sddm.log)
[install-12-215739_zsh.log](https://github.com/JaKooLit/Fedora-Hyprland/files/13923989/install-12-215739_zsh.log)

**Comment by JaKooLit** [comment]
it says you have already all installed necessary zsh apps..

I believe you already have default zsh as your shell thats why it comes error that it didnt change

**Comment by JaKooLit** [comment]
and you failed to inform that it is nobara

be informed that may or may work in nobara. And if log states that sddm theme already changed

**Comment by notna-k** [comment]
Still have same problem, using Fedora 39

**Comment by JaKooLit** [comment]
any update?

**Comment by JaKooLit** [comment]
closing as no more update from OP
