### ISSUE TITLE
[Bug]: .sh script interfaces have huge fonts

### ISSUE THREAD

**Issue by SkepticSeptic** [JaKooLit/Fedora-Hyprland#23]
### Description

When using things such as waybar style selectors, music station selectors, wallpaper selectors, etc. the font is too big to be legible, ending up being cut off

### Steps to Reproduce

This is on a Fedora Asahi Linux machine, so I understand the issue may stem from that. Please let me know if any log files or anything are needed.

### Expected Behavior

Text to either be modifiable or smaller, changing Monitors.conf resolution did not fix this either

### Actual Behavior

No way to change this as of now 

### Screenshots

![image](https://github.com/JaKooLit/Fedora-Hyprland/assets/87040881/fb613d5b-f55a-47a9-bb40-3dce7657f7dd)

![image](https://github.com/JaKooLit/Fedora-Hyprland/assets/87040881/849d7222-9522-4500-8dbd-a6b43f53a60e)

### Environment

- Linux Distro: Asahi Linux Fedora 39
- Linux Version, output of `uname -a`: 
Linux skepf-macbookpro 6.6.3-411.asahi.fc39.aarch64+16k #1 SMP PREEMPT_DYNAMIC Tue Dec 19 10:21:20 UTC 2023 aarch64 GNU/Linux
- Hyprland Version, output of `hyprctl version`: 
Hyprland, built from branch HEAD at commit 03ebbe18ed8517ee22591eac82cd54322f42cb7d  (props: bump ver to 0.34.0).
Date: Mon Jan 1 12:03:15 2024
Tag: v0.34.0

flags: (if any)
- Installation Environment: [e.g., On The Main Hardware, On A Virtual Machine]
Hardware

**Comment by JaKooLit** [comment]
this is not a bug... 

you probably chosen 1440p as resolution 

plus youre on a vm

change all rofi styles with smaller font or choose 1080p

**Comment by SkepticSeptic** [comment]
I did choose 1440p, as the Macbook Pro 13inch's resolution is 2560x1600. This is bare metal on the Mac, no VM's. 

For anyone else facing this: my current less than satisfactory solution is to put the menu in fullscreen. Will try changing rofi styles with a global variable so that others can fix this properly too.

**Comment by SkepticSeptic** [comment]
Found a solution, modifying the rofi-Beats file like so:

nano ~/.config/rofi/config-rofi-Beats.rasi
Change "font:" to whatever size you want, I found 7 to be a good size.

**Comment by JaKooLit** [comment]
ah... Im guessing you change the scaling to either 1.25 or 1.5

anyway, yeah, you just need to modify the rofi font size to your liking.

unfortunately, it does not follow the % like waybar so have to put a "fixed" font size

**Comment by SkepticSeptic** [comment]
Yep, honestly I think it would be a good idea to add rofi configs to the view/edit hyprland configs
