### ISSUE TITLE
Anyway to install your dotfiles on fedora only adjust settings for hyprland? 

### ISSUE THREAD

**Issue by orcbolg3612** [JaKooLit/Fedora-Hyprland#29]
I have gnome base with fedora 39 and it's have somethings adjusted when i installed your dotfiles. I want your dotfiles onlywork work with hyprland and don't touch gnome. Is there anyway?

**Comment by JaKooLit** [comment]
it should not touch your gnome... however, the gtk themes might change...

I dont set to remove anything apart from mako and dunst as it conflicts with swaync

**Comment by orcbolg3612** [comment]
> it should not touch your gnome... however, the gtk themes might change...
> 
> I dont set to remove anything apart from mako and dunst as it conflicts with swaync

Some keyboard shorcuts have bugs when i installed your dotfiles if using gnome. And it can't changable from gnome-settings

**Comment by orcbolg3612** [comment]
Sorry, this error only work when i installed your zsh settings.

**Comment by orcbolg3612** [comment]
Is there a way to enable less blur as default on your dotfiles?

**Comment by orcbolg3612** [comment]
also gamemode?
