### ISSUE TITLE
weird 'blue shadow/? and titlebar text' shown above app window (floating mode) 

### ISSUE THREAD

**Issue by slashedzer0** [JaKooLit/Fedora-Hyprland#3]
![Screenshot_2023-09-24-12-32-29_22767](https://github.com/JaKooLit/Fedora-Hyprland/assets/101719469/21a12354-6937-48db-acf4-a4866e7c18ce)

### bug description
the bug only appear when on floating mode, doesn't matter the window is focused or not. i've also tried to disabling/enabling some settings (nvidia section) in `ENVariables.conf` but no luck.

### additional info
OS: fedora 38 kde (all packages are up-to-date)
GPU: nvidia gtx 1050 (laptop)

**Comment by JaKooLit** [comment]
looks like you toggle the group mode.

mainmode G


review Keybinds.conf and Settings.conf in

~/.config/hypr/configs

**Comment by slashedzer0** [comment]
yup, problem solved. thanks!
