### ISSUE TITLE
add keyboard layout

### ISSUE THREAD

**Issue by Raheem-Ansary** [JaKooLit/Fedora-Hyprland#31]
Hello, I want to add the Persian language to my keyboard, but I am not successful

input {
    kb_layout = us,ir
    kb_options = grp:alt_shift_toggle
}

grep -i 'persian' /usr/share/X11/xkb/rules/base.lst

I put this code in the Hyperland config file, but it didn't work. Thank you for your help

**Comment by JaKooLit** [comment]
sorry took long to reply.

How did it go?

**Comment by Raheem-Ansary** [comment]
no problem sir

I was able to solve it
