### ISSUE TITLE
nwg-look `v0.2.7` breaks installation script (nwg-look portion)

### ISSUE THREAD

**Issue by TonyTwoStep** [JaKooLit/Fedora-Hyprland#33]
## Bug Report
Your script uses the latest version of the `main` branch of the nwg-look repo. The lastest version v0.2.7 requires `go` >= 1.22 whereas the rest of your install script results in an installation of `go` 1.21 on a clean install of Fedora 39 Sway Spin.

This causes the `nwg-look.sh` script to fail to build.

View full changelog at the tag below:
https://github.com/nwg-piotr/nwg-look/releases/tag/v0.2.7

```
...
[NOTE] Installing nwg-look
 nwg-look directory already exists. Updating...
No local changes to save
Already up to date.
go build -v -o bin/nwg-look .
go: go.mod requires go >= 1.22 (running go 1.21.7; GOTOOLCHAIN=local)
make: *** [Makefile:13: build] Error 1
```

I was able to work around this locally by checking out the prior version of the repo to this release, modifying your script to not pull `main`, and re-running, but consider pinning specific versions of your deps in your repo/scripts so unexpected upstream releases don't impact the usability without warning.

**Comment by rpstreef** [comment]
v0.2.5 seems to work fine, i manually did a checkout and build

**Comment by JaKooLit** [comment]
https://github.com/JaKooLit/Fedora-Hyprland/commit/013be48b8d5c7d6a2a6a7784cae1368348865c0c

![Screenshot_01-May_12-50-25_22682](https://github.com/JaKooLit/Fedora-Hyprland/assets/85185940/e3a642e7-e35f-4db6-b949-fedf33454c3a)
