### ISSUE TITLE
[Bug]: error on waybar

### ISSUE THREAD

**Issue by shabbir23ah** [JaKooLit/Fedora-Hyprland#34]
## Bug Report
After opening my PC suddenly this appeared on home screen. Everything else works fine.
### Description

- Linux Distro: Fedora 39
- Linux fedora 6.7.6-200.fc39.x86_64 
- Hyprland Version 0.36.0
- On The Main Hardware

I have attached the screenshot 
![k0HKEfEN](https://github.com/JaKooLit/Fedora-Hyprland/assets/56797263/0b4fa48b-6a6a-4e1f-bbd0-2326eed652f5)
![0ilpdd1H](https://github.com/JaKooLit/Fedora-Hyprland/assets/56797263/86d4a73f-58f9-42e4-8588-836f8de680fe)

**Comment by JaKooLit** [comment]
https://github.com/JaKooLit/Hyprland-Dots/commit/d152871475cee8b9fd0f43fea6267def699445a9

this was fixed by latest Dots released

**Comment by shabbir23ah** [comment]
How do I update?
`git pull` then run `install.sh`  ?

**Comment by JaKooLit** [comment]
https://github.com/JaKooLit/Hyprland-Dots/wiki/Install_&_Update

**Comment by shabbir23ah** [comment]
Thanks!
