### ISSUE TITLE
[Custom]: How to change terminal font

### ISSUE THREAD

**Issue by MrKK4** [JaKooLit/Fedora-Hyprland#36]
### Description

I just installed your script on a fresh installed fedora VM. Everything works seamlessly but the fonts on the terminal seems a little off like the default font that comes pre installed, I know the script installs very good fonts but it's not here. BTW, I change the terminal to foot as kitty won't open in VM and also I didn't installed nwg-look (can it fix that issue)

### Expected Behavior

I think it should load the downloaded fonts

### Actual Behavior

normal fonts showing

### Screenshots (if applicable)

![image](https://github.com/JaKooLit/Fedora-Hyprland/assets/94269452/a6aed306-5c30-44ca-9517-24f4e553878b)

**Comment by JaKooLit** [comment]
https://github.com/JaKooLit/Hyprland-Dots/wiki/FAQ#%EF%B8%8F-adjusting-fonts-sizes-and-font-scaling-including-waybar-fonts-and-kitty-terminal

**Comment by MrKK4** [comment]
I know you can change it for kitty but I want to do it for foot as kitty won't open in VM (Didn't I mention?).

**Comment by JaKooLit** [comment]
then change foot config

**Comment by MrKK4** [comment]
Sorry Mr. Jay but that's what I'm asking (How to change foot terminal config file) but it's ok you might be busy I just copied your foot config file from your previous hyprland dots which worked earlier.
