### ISSUE TITLE
[Bug]: Config file error notification

### ISSUE THREAD

**Issue by rushmi0** [JaKooLit/Fedora-Hyprland#37]
### Description

from the notification at /home/milko/.config/hypr/UserConfigs/Startup_Apps.conf

there is a problem at line 44, but line 44 does not configure anything.

### Steps to Reproduce

1. [ install Fedora-Hyprland ]
2. [ reboot ]

### Expected Behavior

1. this error notification has a problem. it must be informative... of the real problem

### Actual Behavior

1. there is a problem with this error notification, It is false

### Screenshots

![swappy-20240313-134452](https://github.com/JaKooLit/Fedora-Hyprland/assets/120770468/afcf3a16-b0e3-47c8-ab75-0dfde2a58605)

e.g.,

- Linux Distro: [ Fedora 39 ]
- Linux Version, output of `uname -a`: Linux fedora 6.7.7-200.fc39.x86_64
- Hyprland Version, output of `hyprctl version`: Hyprland, built from branch main at commit a065b481f32f4297596a9cd9c538794fd4669b1a 
- Installation Environment: [ On The Main Hardware ]

**Comment by JaKooLit** [comment]
thanks for this

edit
~/.config/hypr/UserConfigs/Startup_Apps.conf


line 44 delete 1 more # . just leave one #
