### ISSUE TITLE
[Bug]: Error in a comment?

### ISSUE THREAD

**Issue by JjersaR** [JaKooLit/Fedora-Hyprland#38]
### Description
I did not modify the logic only save or image paths and now that I entered Hyprland I get this error.

### Steps to Reproduce

1. Change the name of the battery and adapter.
2. Change the wallpaper path
3. Add the stack to the waybar layout

### Expected Behavior

[What did you expect to happen?]
Do not display this error

### Actual Behavior

[What actually happened?]
Error is not removed

### Screenshots
![Screenshot_17-mar_09-43-35_12911](https://github.com/JaKooLit/Fedora-Hyprland/assets/86206596/4c7b5ad2-d4ad-4d7b-bdc5-ddd66543b500)
This is the file I have from UserConfigs/Startup_Apps.conf:
https://gist.github.com/JjersaR/a9416f150d1a3a3da1be9b11d16c017b

### Environment
Line 12 of the hyprland.conf file is this: source= $UserConfigs/Startup_Apps.conf
In the UserConfigs/Startup_Apps.conf file line 44 is this:
## Here is the list of features available but disabled by default.

e.g.,

- Linux Distro: [Fedora 39]
- Linux Version, output of `uname -a`: Linux j 6.7.9-200.fc39.x86_64 #1 SMP PREEMPT_DYNAMIC Wed Mar  6 19:35:04 UTC 2024 x86_64 GNU/Linux
- Hyprland Version, output of `hyprctl version`:
Hyprland, built from branch HEAD at commit c5e28ebcfe00a510922779b2c568cfa52a317445  (props: bump ver 0.37.1).
Date: Sat Mar 16 14:51:49 2024
Tag: v0.37.1

flags: (if any)
- Installation Environment: Main Hardware
- Other info:

### Additional Information
I turned on the computer, it took a while to start hyprland and then it showed the error

**Comment by JaKooLit** [comment]
https://github.com/JaKooLit/Fedora-Hyprland/issues/37

**Comment by JjersaR** [comment]
Thank you very much, it has been solved
