### ISSUE TITLE
Exit-Menu too small on low res

### ISSUE THREAD

**Issue by s4msy** [JaKooLit/Fedora-Hyprland#4]
Hi,
first I really like your work, and installed on two different systems, on the pc with a high resolution everything is fine, but my old laptop with: 1366x768 the exit or logout menu is too small. Any fix here or a hint where I can setup a larger window size. I read all the configs but didnt find it.

Screenshot:
![Screenshot_2023-10-23-19-42-54_8397](https://github.com/JaKooLit/Fedora-Hyprland/assets/13768991/4213d554-1134-47e5-8872-7fe51dde0e7b)

**Comment by JaKooLit** [comment]
You can edit WofiPower.sh which is located in

~/.config/hypr/scripts/

you can change height and width according to your needs.

most scripts inside that folder, you can set the desired height and width
