### ISSUE TITLE
[Bug]: Font and Icon Colors and klipper

### ISSUE THREAD

**Issue by Linxford** [JaKooLit/Fedora-Hyprland#41]
## Bug Report
I just installed hyprland on

     ```
Static hostname: xxxx
           Icon name: computer-laptop
             Chassis: laptop 💻
          Machine ID: xxxxxxxxxxxxxxxxxxxxxxxxxxx
             Boot ID: xxxxxxxxxxxxxxxxxxxxxxxxxxxx
    Operating System: Fedora Linux 39 (KDE Plasma)    
         CPE OS Name: cpe:/o:fedoraproject:fedora:39
      OS Support End: Tue 2024-11-12
OS Support Remaining: 7month 2w 6d
              Kernel: Linux 6.7.9-200.fc39.x86_64
        Architecture: x86-64
     Hardware Vendor: Dell Inc.
      Hardware Model: Latitude 7480
    Firmware Version: 1.36.0
       Firmware Date: Mon 2024-01-29
        Firmware Age: 1month 3w 2d
```

### Description

after installation everything went well, until i i saw that, when i open dolpin file manager, the icons are not showing (something pertaining to the color) it looks dark...

and also my wlogout buttons are too big, if i try too modify the css, then everything becomes pure white ... i mean the bg

### Screenshots

WLOGOUT
![Screenshot_23-Mar_09-38-05_20376](https://github.com/JaKooLit/Fedora-Hyprland/assets/98231918/968be624-a36c-474a-9a37-1ebd2a37b894)

Dolphin
![Screenshot_23-Mar_09-40-34_20404](https://github.com/JaKooLit/Fedora-Hyprland/assets/98231918/139e6af8-9c8c-4610-af53-fb7c2af4b400)

### Environment
- Linux Distro: [ Fedora 39 ]
- Linux Version, Linux xxxx 6.7.9-200.fc39.x86_64 #1 SMP PREEMPT_DYNAMIC Wed Mar  6 19:35:04 UTC 2024 x86_64 GNU/Linux
- Hyprland Version, output of `hyprctl version`: Hyprland, built from branch HEAD at commit c5e28ebcfe00a510922779b2c568cfa52a317445  (props: bump ver 0.37.1).
Date: Sat Mar 16 14:51:49 2024
Tag: v0.37.1
- Installation Environment: [On The Main Hardware]
- Other info: [[e.g., Display Resolution, Resolution, etc](dimensions:    1920x1080 pixels (508x285 millimeters)) and 1600x900 external monitor]

**Comment by JaKooLit** [comment]
any changes here?
