### ISSUE TITLE
[Bug]: Short description of the issue

### ISSUE THREAD

**Issue by coacharnold1** [JaKooLit/Fedora-Hyprland#45]
Hello

So I've updated to Fedora 40 Beta on my HP-chromebox. I assumed it wouldn't be perfect. Here are the issues:

On boot it drops back to the default log in manager and gives an error that it couldn't load ssdm because it didn't see "qtgraphicaleffects" as called for in the ssdm config file. QTgraphicaleffects is installed

I log in and hyprland works perfect with the exception of the wallpaper .... The wallpaper loads without color and is distorted, EVRYTHING else shows perfect. attached is a screen shot:

If anyone has any thoughts here let me know,  I realize i'm operating on beta stuff.  I'm hoping this can help out the Fedora 40 Script when it's ready.

Tim 
![swappy-20240329-123930](https://github.com/JaKooLit/Fedora-Hyprland/assets/30500110/78b641e3-3a19-4f97-90c8-991bdadc2a09)

**Comment by JaKooLit** [comment]
https://github.com/JaKooLit/Hyprland-Dots/issues/184

Ill leave this open so it wont be asked over and over. its swww issue and until swww updated their build, I wont do anything.

but a work around

**Comment by coacharnold1** [comment]
Thank you jakooLit...  i amused there was gonna be some issues going to beta...  if this is the worst of it ...  we are good.  THank you  For the info

**Comment by Motchi0731** [comment]
Had this issue with opensuse

**Comment by Motchi0731** [comment]
There is a workaround, add this to your Startup_Apps.conf located at /home/USER/.config/hypr/UserConfigs

exec-once = swww-daemon --format xrgb

Below is the reference to the workaround.
[https://github.com/LGFae/swww/issues/233]

**Comment by JaKooLit** [comment]
closing this as the swww developer have fixed the issue

https://github.com/LGFae/swww/issues/233
