### ISSUE TITLE
Unable to login while using Hyprland

### ISSUE THREAD

**Issue by lawsonguilbeau** [JaKooLit/Fedora-Hyprland#48]
### Steps to Reproduce

1. [Use the Fedora-Hyprland installer]
2. [Reboot system]
3. [Go to login]
4. [Get sent back to the login screen after inputting password]

### Expected Behavior

[Expected the Hyprland environment to load]

### Actual Behavior

[I get sent back to the login screen after I input my password]

- Linux Distro: [Fedora 39]
- Installation Environment: [Non Nvidia]

**Comment by ItsVanishCat** [comment]
I've got same issue

**Comment by JaKooLit** [comment]
are you on a VM? or real hardware?

**Comment by lawsonguilbeau** [comment]
@JaKooLit I am using real hardware.

**Comment by JaKooLit** [comment]
> @JaKooLit I am using real hardware.

what happen if you start Hyprland manually?

**Comment by JaKooLit** [comment]
whats the status of this?

**Comment by ItsVanishCat** [comment]
> whats the status of this?

def not closed as i still have the issue, i've lost interest on keep going with it as i just downloaded the dots myself, thanks anyways

**Comment by JaKooLit** [comment]
![Screenshot_01-May_19-36-09_25056](https://github.com/JaKooLit/Fedora-Hyprland/assets/85185940/a6d9f130-0086-445d-bbea-4d061c11bebc)

**Comment by carlwarnick** [comment]
Same issue as above.  A virtual machine using fedora 41 workstation standard install of hyprland.

**Comment by JaKooLit** [comment]
use qemu-kvm

vbox and vmware sucks

**Comment by carlwarnick** [comment]
using qemu from UTM  4.64 arch64
