### ISSUE TITLE
[Bug]: Can't go past the login screen

### ISSUE THREAD

**Issue by ispkd** [JaKooLit/Fedora-Hyprland#49]
### Description

Well, just finished doing the install, reboot, login, sends me to login again, again, again...

### Steps to Reproduce

1. Start computer
2. Select Hyprland as WM in gnome login
3. Login infinitely as it won't load Hyprland

### Expected Behavior

Start Hyprland and waybar?

### Actual Behavior

Can't go past the login screen as it redirects me back when using Hyprland

### Screenshots

Nope.

### Environment

- Linux Distro: Fedora 39
- Linux Version: Linux fedora 6.8.4-200.fc39.x86_64 #1 SMP PREEMPT_DYNAMIC
- Installation Environment: Main machine, dualboot with windows.
- Other info: 1920x1080@60 fresh install, no additional packages

### Additional Information

Just installed fedora.

**Comment by JaKooLit** [comment]
I just updated the script. Please re download the script and re-ran again. Please take now of the readme


![Screenshot_01-May_12-50-25_22682](https://github.com/JaKooLit/Fedora-Hyprland/assets/85185940/23bd94ce-4796-453a-9fe6-671887b60853)

**Comment by JaKooLit** [comment]
closing as no more update from the OP

**Comment by alliesaround** [comment]
I have the same exact issue is three days im trying (using a VM and yes 3D accelleration is on)

**Comment by alliesaround** [comment]
the only option i have is the Hyprland the uswm one is not there
