### ISSUE TITLE
How to change the wallpaper to any wallpaper I want?

### ISSUE THREAD

**Issue by PeDro0210** [JaKooLit/Fedora-Hyprland#50]
I'm pretty noob at linux and I just setup up Hyprland, So I was messing around with it, but didn't find a way to use a costume wallpaper.

**Comment by PeDro0210** [comment]
I just found out how to add a wallpaper :D

**Comment by JaKooLit** [comment]
https://github.com/JaKooLit/Hyprland-Dots/wiki/FAQ#%EF%B8%8F-how-to-change-wallpaper

**Comment by PeDro0210** [comment]
thx :D
