### ISSUE TITLE
[Bug]: Line 7 In UserSettings.conf Glob error

### ISSUE THREAD

**Issue by nevermore23274** [JaKooLit/Fedora-Hyprland#57]
### Description

It states that line 7 in /home/{user}/.config/hypr/UserConfigs/UserSettings.conf has issues.  (other errors listed but they all seem to come back to this line)

### Steps to Reproduce

1. Updated system
2. Errors popped up

### Expected Behavior

No errors.

### Actual Behavior

Errors.

### Screenshots

![Screenshot_21-Apr_22-38-38_30274](https://github.com/JaKooLit/Fedora-Hyprland/assets/18754037/6bae7eab-4afb-44c1-9647-740a1c298d2d)

### Environment

OS: Fedora Linux 39 (Workstation Edition) x86_64 
Host: Surface Pro 8 (using linux kernel)
Kernel: 6.8.6-1.surface.fc39.x86_64

Hyprctl version output:
Hyprland, built from branch  at commit fe7b748eb668136dd0558b7c8279bfcd7ab4d759  (props: bump version to 0.39.1).
Date: Tue Apr 16 16:01:03 2024
Tag: v0.39.1, commits: 4460

### Additional Information

None for now.

**Comment by JaKooLit** [comment]
Those are pywal colors......

check if pywal is installed... if so, you just need to reboot your system to refresh.. 

You said you updated, did you reboot?

**Comment by nevermore23274** [comment]
> Those are pywal colors......
> 
> check if pywal is installed... if so, you just need to reboot your system to refresh..
> 
> You said you updated, did you reboot?

Yes, I rebooted. As well, checking the pywal github and running `printf "%b" "\033]11;#ff0000\007"` turns my terminal red so I assume it's certainly installed.

The location of `source = $HOME/.cache/wal/colors-hyprland` doesn't actual exist. Instead, the only two folders in there are:

- colorschemes
- templates

colorschemes has:
- dark
- light

and templates has:
- cava-colors
- colors-hyprland
- colors-rofi-dark.rasi
- colors-rofi-light.rasi

Would I be correct in assuming the `templates` folder is what it's seeking so I can just redirect the UserSettings.conf?

**Comment by nevermore23274** [comment]
I changed `source = $HOME/.cache/wal/colors-hyprland` to `source = $HOME/.cache/wal/templates/colors-hyprland` and rebooted, no fix. However, changed it back to `source = $HOME/.cache/wal/colors-hyprland` and suddenly the errors went away.....No idea how or why this fixed it, but thanks for the help.

**Comment by JaKooLit** [comment]
can you try to run this command?

~/.config/hypr/scripts/PywalSwww.sh

this should try to execute the current wallpapers pywal color scheme
