### ISSUE TITLE
[Suggestion] you could create a custom image with Hyprland

### ISSUE THREAD

**Issue by Heus-Sueh** [JaKooLit/Fedora-Hyprland#6]
You could create a customized image with hyprland using ublue as a base and everyone could use your customization just by giving the command ``rpm-ostree rebase``

1. https://universal-blue.org/introduction/

**Comment by JaKooLit** [comment]
This looks interesting... although I dont have time to figure that out 😀

**Comment by JaKooLit** [comment]
no plan cause that would mean I have to maintain that image
