### ISSUE TITLE
[Feature Request]: update to wget

### ISSUE THREAD

**Issue by Linxford** [JaKooLit/Fedora-Hyprland#61]
Wget is no more working during the Installation... 

From the link below... it shows wget2  is the current version to be used... kindly update

(https://packages.fedoraproject.org/pkgs/wget2/wget2-wget/fedora-40.html)

**Comment by JaKooLit** [comment]
fedora installers in general will pull the closest package match and wget is not an exemption

![Screenshot_26-Apr_06-45-09_18842](https://github.com/JaKooLit/Fedora-Hyprland/assets/85185940/18d9a087-2bd8-40ff-91de-db8a2b7dd9af)
