### ISSUE TITLE
Suggestion: Create an uninstallation script

### ISSUE THREAD

**Issue by Jeymen** [JaKooLit/Fedora-Hyprland#7]
Hi! I would suggest adding an uninstall script for less-Linux-savvy users like me. I can't find any resources on how to uninstall Hyprland.
Thank you, Jeymen.

**Comment by JaKooLit** [comment]
Hi... Issue is if create an uninstall, I dont know the effect on your system and may break cause there are shared libraries

to remove hyprland

sudo dnf autoremove hyprland-git

on the other hand, there are also packages which is needed by dots in which, could be already installed by system or added during installation.

**Comment by Jeymen** [comment]
Makes sense since the script is also installing other things such as driver. Didn't know the name of the hyprland package, perhaps why I didn't try dnf remove. Thank you for the help.
