### ISSUE TITLE
[Bug]: Workspace disappears

### ISSUE THREAD

**Issue by JjersaR** [JaKooLit/Fedora-Hyprland#75]
## Bug Report
I upgraded my Fedora Workstation system to version 40 and now I can't see what workspace I'm in.

### Description
This is how it currently looks
![Screenshot_03-may_19-44-52_29952](https://github.com/JaKooLit/Fedora-Hyprland/assets/86206596/c019d084-0939-4fb3-8b44-6eeb11b1fbf0)

When it used to show something like this next to the update logo
![Screenshot_03-may_19-46-13_19029](https://github.com/JaKooLit/Fedora-Hyprland/assets/86206596/e2c82810-019b-4f78-8361-093f308ba221)

### Steps to Reproduce
Just upgrade the system from Fedora 39 to Fedora 40
Kernel: 6.8.8-300.fc40.x86_64 

### Expected Behavior
I hope to see the workspace together with the logo of the upgrades

### Actual Behavior
I can't see the workspace and the code I have in ~/.config/waybar/config is this:
`"modules-center": [
	"hyprland/workspaces",
	"custom/separator#blank",
  "custom/updater"
],
`

### Environment

[Please add any other relevant information about the bug and remove the unnecessary lines.]

e.g.,

- Linux Distro: Fedora 40
- Linux Version, output of `uname -a`:
- Hyprland Version, output of `hyprctl version`: Linux j 6.8.8-300.fc40.x86_64 #1 SMP PREEMPT_DYNAMIC Sat Apr 27 17:53:31 UTC 2024 x86_64 GNU/Linux
- Installation Environment: The Main Hardware
- Other info: The resolution is 1920 x 1080

**Comment by JaKooLit** [comment]
weird...

perhaps a reboot? or reinstall hyprland and or waybar

**Comment by JjersaR** [comment]
Before moving to Fedora 40 upgraded hyprland and waybar, but possibly reinstalling waybar would work.

**Comment by JaKooLit** [comment]
yes everything SHOULD be update before upgrading to fed 40 as per fedora wiki. Its a pre requisite before ugrading to next release.

and then some packages, may break in that process and normally, reinstalling and reboot does the trick

**Comment by JjersaR** [comment]
I already tried reinstalling waybar and it didn't work, it keeps showing only the updates logo.

**Comment by JjersaR** [comment]
Thank you very much for your help, so i'll change the version of waybar

**Comment by JaKooLit** [comment]
no downgrade the hyprland or build the latest waybar from source

https://github.com/Alexays/Waybar

**Comment by EdgyGuy19** [comment]
I just got the same issue after I used dnf update and system reboot

**Comment by JaKooLit** [comment]
> I got a similiar issue after dnf update. On one of my machines I can't see workspace icon and on another machine the waybar is just messed up with icons in the wrong order and no workspace icons as well.

alot of fix on going with waybar... Fedora just need to update their repo.. if you cant wait, you can build either from source or releases of waybar
