### ISSUE TITLE
XDG autostart items not loading from user folder

### ISSUE THREAD

**Issue by RedBearAK** [JaKooLit/Fedora-Hyprland#8]
I have a couple of items (desktop entry files) that I place in ~/.config/autostart when I install my project. Normally on most desktop environments, when you log into the desktop these items will start automatically. This doesn't seem to be happening on the Hyprland setup after using this script on Fedora 39. They do get loaded when logging into GNOME on the same system. 

Is there a specific reason why the items in ~/.config/autostart aren't being loaded? Can we fix the setup of Hyprland so that this standard XDG spec is recognized as a way to load things on login? 

One of the startup items runs a command that lets a background systemd service start correctly, and the other puts a tray icon in the indicator tray on the bar. When I run these things manually they work fine in Hyprland. But I need them to run automatically or the service doesn't work until it gets manually restarted later. 

I'm sure there is some Hyprland-specific way to start things on login, but it would be nice if the same standard recognized by other desktop environments would work with this setup script. 

I kind of thought systemd was responsible for loading the items in the ~/.config/autostart folder, but that doesn't seem to be happening in this case. 

Awesome project. Thanks for fixing the key bindings in the dotfiles. Works much better now.

**Comment by JaKooLit** [comment]
> Awesome project. Thanks for fixing the key bindings in the dotfiles. Works much better now.

well thanks for letting me know. I use codium and thunar but I dont really use the keyboard shortcuts (much) so I didnt check the conflicts. But now, need to be careful in assigning keyboard shortcuts in the future... Im actually surprised nobody has mentioned this before 🤣


Regarding the autostart of apps, Hyprland or any other WM, does not work like that.... 
They dont work like a normal DE type.

If you want to add or to autostart your favorite apps, you can add them in ~/.config/hypr/configs/Execs.conf

as per wiki
https://wiki.hyprland.org/

you need to add it in hyprland.conf in ~/.config/hypr BUT on my config, I broke down the hyprland.conf for easy referrence, and easy to do changes if desired rather than navigating through long list in hyprland.conf

**Comment by RedBearAK** [comment]
@JaKooLit 

>  Im actually surprised nobody has mentioned this before 🤣

I also find that the most confusing aspect. As if people were not closing tabs with the keyboard, or even using tabs at all. Which seems unlikely. I had thought tiling WMs have a tendency to draw users that love to use the keyboard for everything. 

>  on my config, I broke down the hyprland.conf for easy referrence, and easy to do changes if desired rather than navigating through long list in hyprland.conf

That seems like a very good idea, making the config info more modular. Nice. 👍🏽 

> you can add them in ~/.config/hypr/configs/Execs.conf

I will look into that, and the original `hyprland.conf` method. Seems like something I may have to leave up to the end user, since the method may vary due to the way most Hyprland users are currently doing manual setups, or using scripts like yours. 

Thanks for the response.

**Comment by RedBearAK** [comment]
@JaKooLit 

In case you are interested in including this in your setup, here is what I did to be able to launch the items in `~/.config/autostart` at startup. Seems to work nicely. The script finds the "Exec=" line from each desktop file and just launches the command, and runs any other executable file it finds in the folder (though I think that's not part of the XDG spec, I think they only care about launching desktop entry files). 

The script logs its actions to the syslog or systemd journal with the `logger` command. 

I put these two lines at the end of `Execs.conf` to call the script: 

```sh
# process the user XDG Autostart folder contents
exec-once = $scriptsDir/XDG-Autostart-processor.sh
```

And this is the script: 

```sh
#!/usr/bin/env bash

# Script to process and launch items in the XDG Autostart user location (~/.config/autostart)


# Function to echo and log a message
log_and_echo() {
    local message="$1"
    echo "$message" | tee >(logger -p user.info)
}


log_and_echo "Processing user XDG Autostart folder contents..."


for entry in ~/.config/autostart/*.desktop; do
    if [[ -f "$entry" ]]; then
        # Extract the Exec command from the desktop entry and execute it
        cmd=$(grep '^Exec=' "$entry" | head -n 1 | sed 's/^Exec=//' | sed 's/%.//g')
        log_and_echo "Launching desktop entry file: '$entry'"
        # shellcheck disable=SC2086
        $cmd > /dev/null 2>&1 &
    elif [[ -x "$entry" ]]; then
        # If the file is executable, run it directly
        log_and_echo "Launching executable file: '$entry'"
        "$entry" > /dev/null 2>&1 &
    fi
done

log_and_echo "Finished processing user XDG Autostart folder contents."
```
