### ISSUE TITLE
[Feature Request]: Add arguments to install script to bypass prompts

### ISSUE THREAD

**Issue by Coelhomatias** [JaKooLit/Fedora-Hyprland#80]
### Description

It would be awesome if the script accepted arguments so that the options could be selected without going through the prompts.
This would be beneficial when using with ansible for example.

**Comment by JaKooLit** [comment]
but that one of the feature, so users can choose what they want to install....

but Ill see if I can use the preset.sh that was on my Arch-Hyprland project

**Comment by Coelhomatias** [comment]
I don't think you understood me right.
I was suggesting something along the lines of running the script with optional arguments, however, whichever option is not answered by the arguments, the user should be prompt.
So if running the script with maybe `instal.sh --nvidia --bluetooth` would assume yes for the nvidia and bluetooth questions but still prompt the user about the remaining questions.

**Comment by JaKooLit** [comment]
oh gotcha.. its a good idea.

**Comment by bmentink** [comment]
do it the other way around. Assume "Yes" and only pass parameters for the "no"

**Comment by JaKooLit** [comment]
no plan.. I dont have time
