### ISSUE TITLE
I want to change Rofi theme 

### ISSUE THREAD

**Issue by digvijayizing** [JaKooLit/Fedora-Hyprland#91]
I tried to change rofi theme but when i followed all the steps it failed 
I am kind of new to this so can you please help me to how can i achieve my desired rofi theme
![swappy-20240529-172725](https://github.com/JaKooLit/Fedora-Hyprland/assets/93901013/76e97bff-fcf3-4cc5-badc-0470e47576e5)

**Comment by JaKooLit** [comment]
https://github.com/JaKooLit/Hyprland-Dots/discussions/315


pls dont open another issue as such

it is not a bug...
