### ISSUE TITLE
[Bug]: Swaylock not working after unspecified time

### ISSUE THREAD

**Issue by Kahan64bit** [JaKooLit/Fedora-Hyprland#93]
### Description

Swaylock will no longer run after lid-close or ctrl+alt+l after an unspecified amount of time

### Hardware Description
- Apple Macbook Pro M1 Pro 14-inch
- Asahi Linux Fedora Workstation 40
- 6.8.10-400.asahi.fc40.aarch64+16k

### Steps to reproduce
This may be an Asahi issue; however, this issue was present from the initial installation using the git script.

### Additional Notes
There are no runtime or other error messages that present themselves when this error occurs, so self-diagnosing was quite difficult.

**Comment by JaKooLit** [comment]
pls take note I dropped the wlogout some time back

https://github.com/JaKooLit/Fedora-Hyprland/blob/main/CHANGELOGS.md#23-apr-2024

**Comment by Kahan64bit** [comment]
Sorry for the confusion. I meant to say this issue is prevalent with Hyprlock and Hypridle. I haven't changed the .config files for any of them. Hypridle just stops working after an unknown amount of time, which leads Hyrlock to not work. I'm honestly pretty new to this, so I don't know where to begin.

**Comment by JaKooLit** [comment]
you can reinstall hypridle and hyprlock

sudo dnf install hypridle hyprlock

**Comment by Kahan64bit** [comment]
Can't believe a simple reinstall fixed the problem. Closing this issue.
