### ISSUE TITLE
I have some Questions

### ISSUE THREAD

**Issue by HuangLinBao** [JaKooLit/Fedora-Hyprland#94]
I've been really interested in hyprland in general ever since it has dropped and even enabled one of the first hyprland copr repos. ended up deleting it and reverting back to gnome to wait for it to become a bit more stable and now I've stumbled here and really interested in using the installer but I have some questions.

1. Fedora has been on my machine for like 2 years and the size of the partition is around 800GB so backing it up using timeshift took ages and ended up with around 5GB left in my partition XD. The question is that weather it's extremely important to create a back up or not.

2. regarding the ASUS ROG thing. will it be okay if I said yes while I have ASUS TUF or is it only for ROG?

**Comment by JaKooLit** [comment]
the backup is entirely up to user.

its not a mandatory...

Ive come up with this as a note since I dont put any uninstall script

**Comment by JaKooLit** [comment]
https://asus-linux.org/

see if your aystem is supported by asusctl

**Comment by HuangLinBao** [comment]
Thanks
