### ISSUE TITLE
Maybe a bug on VPN connections

### ISSUE THREAD

**Issue by PedroBuffon** [JaKooLit/Fedora-Hyprland#95]
Using Fedora 40, default install of the script, i use wireguard as a vpn, when setting up wireguard on hyprland, the setup can be done normaly but when tried to connect via waybar it appears that the button dont work, on "VPN connections" it shows the wireguard connection, but clicking on it doesn`t do anything.

**Comment by JaKooLit** [comment]
I have not setup for any vpn... 

waybar module maybe there but it is not a guaranteed to fully work

**Comment by JaKooLit** [comment]
closing as no reply
