### ISSUE TITLE
[Bug]: Clipboard isn't functioning correctly, and sometimes doesn't function at all :(

### ISSUE THREAD

**Issue by ZenDeuo** [JaKooLit/Fedora-Hyprland#96]
### Description

Pasting Issues and I'm unsure how to fix it.

### Steps to Reproduce

1. Copy text from Chrome
2. Attempt to paste into Discord and it doesn't work

### Expected Behavior

For the text that I copied to be pasted.

### Actual Behavior

It doesn't do anything

### Environment

Nobara KDE but installed Hyprland Fedora. Also I noticed that when copying text from say 1Password it can be pasted into Discord with the Middle Mouse Button and not Control + V, this is the same in Google Chrome but it's also weird because if I Control + C from a website, it is pastable, but if I copy the URL from the URL Bar it is not pastable it's like it doesn't even get copied and I'm not sure what's going on and how to fix it.

- Linux Distro: Nobara 39 KDE (but installed this Fedora-Hyprland and still have KDE installed)
- Linux Version, output of `uname -a`: Linux DeuoDesk 6.8.12-200.fsync.fc39.x86_64 #1 SMP PREEMPT_DYNAMIC TKG Sat Jun  1 23:00:12 UTC 2024 x86_64 GNU/Linux
- Hyprland Version, output of `hyprctl version`: Hyprland, built from branch  at commit ea2501d4556f84d3de86a4ae2f4b22a474555b9f  (props: bump version to 0.41.0).
Date: Mon Jun 10 14:23:06 2024
Tag: v0.41.0, commits: 4794

flags: (if any)
- Installation Environment: On Main Hardware
- Other info: 1920x1080@144hz and 1920x1080@60hz

### Additional Information
Some of the information above may be incorrect because I had to type it all manually. Thanks Clipboard 😭

### show output of `inxi -CGIsSMnr` install package `inxi` if not exist
show output here
```
System:
  Host: DeuoDesk Kernel: 6.8.12-200.fsync.fc39.x86_64 arch: x86_64 bits: 64
  Desktop: Hyprland v: 0.41.0 Distro: Nobara Linux 39 (KDE Plasma)
Machine:
  Type: Desktop System: CMS s product: 7200-5524B v: N/A
    serial: <superuser required>
  Mobo: ASUSTeK model: PRIME H310M-A R2.0 v: Rev X.0x
    serial: <superuser required> UEFI: American Megatrends v: 2208
    date: 07/09/2021
CPU:
  Info: 6-core model: Intel Core i5-9400F bits: 64 type: MCP cache:
    L2: 1.5 MiB
  Speed (MHz): avg: 2400 min/max: 800/4100 cores: 1: 2400 2: 2400 3: 2400
    4: 2400 5: 2401 6: 2400
Graphics:
  Device-1: NVIDIA TU106 [GeForce RTX 2060 Rev. A] driver: nvidia v: 555.42.02
  Display: wayland server: X.org v: 1.20.14 with: Xwayland v: 24.1.0
    compositor: Hyprland v: 0.41.0 driver: N/A resolution: 1: 1920x1080
    2: 1920x1080
  API: EGL v: 1.5 drivers: nvidia,swrast,zink
    platforms: gbm,wayland,x11,surfaceless,device
  API: OpenGL v: 4.6.0 compat-v: 4.5 vendor: nvidia mesa v: 555.42.02
    renderer: NVIDIA GeForce RTX 2060/PCIe/SSE2
  API: Vulkan v: 1.3.280 drivers: N/A surfaces: xcb,xlib,wayland
Network:
  Device-1: Realtek RTL8111/8168/8211/8411 PCI Express Gigabit Ethernet
    driver: r8169
  IF: enp4s0 state: up speed: 1000 Mbps duplex: full mac: a8:5e:45:5b:65:28
  IF-ID-1: virbr0 state: down mac: 52:54:00:52:9b:d1
Sensors:
  System Temperatures: cpu: 40.0 C mobo: N/A
  Fan Speeds (rpm): N/A
Repos:
  No active dnf repos in: /etc/dnf/dnf.conf
  Active yum repos in: /etc/yum.repos.d/1password.repo
    1: 1password ~ https://downloads.1password.com/linux/rpm/stable/$basearch
  Active yum repos in: /etc/yum.repos.d/_copr:copr.fedorainfracloud.org:codifryed:CoolerControl.repo
    1: copr:copr.fedorainfracloud.org:codifryed:CoolerControl ~ https://download.copr.fedorainfracloud.org/results/codifryed/CoolerControl/fedora-$releasever-$basearch/
  Active yum repos in: /etc/yum.repos.d/_copr:copr.fedorainfracloud.org:erikreider:SwayNotificationCenter.repo
    1: copr:copr.fedorainfracloud.org:erikreider:SwayNotificationCenter ~ https://download.copr.fedorainfracloud.org/results/erikreider/SwayNotificationCenter/fedora-$releasever-$basearch/
  Active yum repos in: /etc/yum.repos.d/_copr:copr.fedorainfracloud.org:solopasha:hyprland.repo
    1: copr:copr.fedorainfracloud.org:solopasha:hyprland ~ https://download.copr.fedorainfracloud.org/results/solopasha/hyprland/fedora-$releasever-$basearch/
  Active yum repos in: /etc/yum.repos.d/brave-browser.repo
    1: brave-browser ~ https://brave-browser-rpm-release.s3.brave.com/$basearch
  Active yum repos in: /etc/yum.repos.d/fedora-cisco-openh264.repo
    1: fedora-cisco-openh264 ~ https://mirrors.fedoraproject.org/metalink?repo=fedora-cisco-openh264-$releasever&arch=$basearch
  No active yum repos in: /etc/yum.repos.d/fedora-updates-testing.repo
  Active yum repos in: /etc/yum.repos.d/fedora-updates.repo
    1: updates ~ https://mirrors.nobaraproject.org/fedora-updates
  Active yum repos in: /etc/yum.repos.d/fedora.repo
    1: fedora ~ https://mirrors.nobaraproject.org/fedora
  Active yum repos in: /etc/yum.repos.d/google-chrome-beta.repo
    1: google-chrome-beta ~ https://dl.google.com/linux/chrome/rpm/stable/x86_64
  Active yum repos in: /etc/yum.repos.d/nextdns.repo
    1: nextdns ~ https://repo.nextdns.io/rpm
  No active yum repos in: /etc/yum.repos.d/nobara-nvidia-new-feature.repo
  Active yum repos in: /etc/yum.repos.d/nobara.repo
    1: nobara-baseos-$releasever ~ https://mirrors.nobaraproject.org/baseos
    2: nobara-appstream-$releasever ~ https://mirrors.nobaraproject.org/appstream
    3: nobara-rocm-official ~ https://repo.radeon.com/rocm/rhel9/6.0.2/main/
    4: nobara-kde6 ~ https://mirrors.nobaraproject.org/kde6
    5: nobara-kde6-overrides ~ https://mirrors.nobaraproject.org/kde6-overrides
  No active yum repos in: /etc/yum.repos.d/rpmfusion-free-updates-testing.repo
  Active yum repos in: /etc/yum.repos.d/rpmfusion-free-updates.repo
    1: rpmfusion-free-updates ~ https://mirrors.rpmfusion.org/metalink?repo=free-fedora-updates-released-$releasever&arch=$basearch
  Active yum repos in: /etc/yum.repos.d/rpmfusion-free.repo
    1: rpmfusion-free ~ https://mirrors.rpmfusion.org/metalink?repo=free-fedora-$releasever&arch=$basearch
  No active yum repos in: /etc/yum.repos.d/rpmfusion-nonfree-updates-testing.repo
  Active yum repos in: /etc/yum.repos.d/rpmfusion-nonfree-updates.repo
    1: rpmfusion-nonfree-updates ~ https://mirrors.rpmfusion.org/metalink?repo=nonfree-fedora-updates-released-$releasever&arch=$basearch
  Active yum repos in: /etc/yum.repos.d/rpmfusion-nonfree.repo
    1: rpmfusion-nonfree ~ https://mirrors.rpmfusion.org/metalink?repo=nonfree-fedora-$releasever&arch=$basearch
Info:
  Memory: total: 16 GiB available: 15.54 GiB used: 3.07 GiB (19.7%)
  Processes: 323 Uptime: 6h 51m Shell: fish inxi: 3.3.34
```
(I'm surprised that managed to get copied)

**Comment by ZenDeuo** [comment]
Update: This literally doesn't make any sense, I can copy text in one app and ONLY paste it within that app, however I can't paste it in any other apps, Chrome is one of these apps that has the issue, I can copy the URL and paste it into a website as long as it's within the Chrome window, it's like my clipboards are contained in their own little boxes for each application.

**Comment by JaKooLit** [comment]
Hi. Im not on my system now but I have an idea of what is happening. Both Chrome and Discord are electron apps, and this cause issues

kindly launch both apps with something like this

discord --enable-features=UseOzonePlatform --ozone-platform=wayland

launch in tty. Do the same for chrome

if it works, you can edit ~/.config/hypr/UserConfigs/ENVariables.conf

there is env = ozone-platform=auto, change the auto to wayland. Log out and login and then try again to lauch the 2 apps normally. ie. from rofi menu

I just type this using my phone so I may have mistyped something

**Comment by ZenDeuo** [comment]
So I launched, Chrome, 1Password and Discord with
chrome --enable-features=UseOzonePlatform --ozone-platform=wayland
Discord --enable-features=UseOzonePlatform --ozone-platform=wayland
1password --enable-features=UseOzonePlatform --ozone-platform=wayland

And it fixed the issue but when I was looking in the environment variables there wasn't an env = ozone-platform=auto even in there, so I had to manually add env = ozone-platform=wayland and rebooted to be sure that it would work and it doesn't so I'm not sure if that's a me problem, I might be missing something here, also I don't mind mistypes and please do take your time as much time as you need or respond when your back on your Computer I don't mind, it's not that urgent for me :) Just a lil bug I'd like to get fixed at some point :) if it doesn't get fixed I might just try installing normal Fedora KDE and then reinstalling this since I don't mind reinstalling stuff or might try reinstalling Nobara KDE, depends on what's easier since I know Nobara is great at getting NVIDIA Drivers to run right out of the box and just have them work immediately and I like that about Nobara where as Fedora is a little more difficult and requires a bit more tweaking but yeah :) Thanks for your support so far I really appreciate it :)

**Comment by JaKooLit** [comment]
https://github.com/JaKooLit/Hyprland-Dots/blob/main/config%2Fhypr%2FUserConfigs%2FENVariables.conf#L27

just remember it should be in

~/.config/hypr/UserConfigs/ENVariables.conf

**Comment by ZenDeuo** [comment]
Okay just applied that change and logged out then back in and the issue still remains, sorta. Copying and pasting from Discord is now functional, copying and pasting from Google Chrome is not functional sort of, copying and pasting within Google Chrome is functional but it won't leave the Chrome Window, it's locked in, it will work within any Chrome Window. The copied stuff in chrome doesn't show up in the cliphist. 1Password is the same as Chrome, pasting inside is okay, pasting outside is not sadly. :) Thanks for your help so far btw I really appreciate it :)

**Comment by JaKooLit** [comment]
as Ive said its electron (most likely) issue and any electron apps will have this issue

**Comment by ZenDeuo** [comment]
Yeah that's fair lol, thanks so much for your support :)
