### ISSUE TITLE
Rofi menus look compressed

### ISSUE THREAD

**Issue by HuangLinBao** [JaKooLit/Fedora-Hyprland#98]
I have this issue using rofi menus for changing the wallpapers and changing waybar styles.

the menu looks compressed like in the photo here
![image](https://github.com/JaKooLit/Fedora-Hyprland/assets/57255961/0b06fad0-4acf-4fec-b5ea-a37e1165d5f2)

it seems to be a problem with the menus for changing wallpapers, waybar style, layout and the config editing menu. App menu appears to be natural

![image](https://github.com/JaKooLit/Fedora-Hyprland/assets/57255961/2e298277-092f-41f1-9a3c-e9bec82442d1)

![image](https://github.com/JaKooLit/Fedora-Hyprland/assets/57255961/2fe11a28-5f8a-4b28-8689-312126c23d7b)

![image](https://github.com/JaKooLit/Fedora-Hyprland/assets/57255961/a34dcdfa-d084-4c6e-8890-93afdc0bd617)

![image](https://github.com/JaKooLit/Fedora-Hyprland/assets/57255961/0722b738-edf5-4e45-908c-5c51823fdef1)

within the installation script I chose the 1080 resolution option since my monitor is 1920x1080

I have no idea how to fix this issue. I went to the config files within the hyprland scripts and rofi config files and tried to understand the lines, but I didn't find anything that I can change the height.

**Comment by JaKooLit** [comment]
sudo dnf autoremove rofi

sudo dnf install rofi-wayland

**Comment by HuangLinBao** [comment]
Thank you very much
