### ISSUE TITLE
[Bug]: unknown option --zsh 

### ISSUE THREAD

**Issue by k1mberlye** [JaKooLit/Fedora-Hyprland#99]
hi im newbie on linux, i install with ur script using fedora 40
and everytime i use kitty it shown unknown option : --zsh
is there any way i can fix it?

**Comment by JaKooLit** [comment]
> hi im newbie on linux, i install with ur script using fedora 40
> and everytime i use kitty it shown unknown option : --zsh
> is there any way i can fix it?

screenshot pls

**Comment by k1mberlye** [comment]
![image](https://github.com/JaKooLit/Fedora-Hyprland/assets/106757239/4ab695ae-740d-4e1a-9028-f2e66b8eaeaa)
here is the screenshot

**Comment by k1mberlye** [comment]
everything is just working fine, but it just anoying to have that uknown option this is for my version 
![image](https://github.com/JaKooLit/Fedora-Hyprland/assets/106757239/503e36eb-2ae3-48c8-8129-901efb62e7aa)

**Comment by JaKooLit** [comment]
https://github.com/junegunn/fzf?tab=readme-ov-file#linux-packages


dang.. fedora have been lazy updating their repo again... as always

you can either install fzf from source

or disable and uninstall fzf

if you decide the latter, 

edit ~/.zshrc & uninstall fzf 
sudo dnf autoremove fzf


I just removed fzf now
you can do same on your system

**Comment by JaKooLit** [comment]
https://github.com/JaKooLit/Fedora-Hyprland/commit/641bcfc9e27b9113cd3390b272ee5d747d71a2f5
